@extends('layouts.metronic.app')

@section('title', 'Target & Bonus')
@section('page_title', 'Target & Bonus Staf')
@section('page_description', 'Pantau target, nilai kinerja, persetujuan, dan pembayaran bonus dalam satu halaman.')

@section('page_guide')
    <x-metronic.page-guide id="staff-bonus-guide" title="Panduan Target & Bonus">
        <x-slot:function><p>Owner menetapkan target bulanan. Sistem menghitung nilai dari data operasional, absensi, dan checklist setiap akun.</p></x-slot:function>
        <x-slot:workflow><ol><li>Owner membuat program untuk bulan berikutnya.</li><li>Pilih KPI, target, bobot, lokasi, dan staf.</li><li>Aktifkan program sebelum bulan dimulai.</li><li>Ajukan hasil setelah periode berakhir.</li><li>Kepala bagian menyetujui hasil, lalu Owner mencatat pembayaran.</li></ol></x-slot:workflow>
        <x-slot:warnings><div class="alert alert-warning mb-0">Program aktif tidak dapat diubah. Pastikan total bobot 100% dan daftar penerima sudah benar sebelum aktivasi.</div></x-slot:warnings>
    </x-metronic.page-guide>
@endsection

@section('content')
@php
    $canTeam = auth()->user()->can('staff_bonuses.view_team') || auth()->user()->can('staff_bonuses.view_all');
    $canManage = auth()->user()->can('staff_bonuses.manage');
    $canDecision = auth()->user()->can('staff_bonuses.approve') || auth()->user()->can('staff_bonuses.pay');
    $tabs = ['mine'=>'Target Saya'];
    if($canTeam) $tabs['team']='Kinerja Tim';
    if($canManage) $tabs['programs']='Program & Target';
    if($canDecision) $tabs['approval']='Persetujuan & Pembayaran';
    if(auth()->user()->can('staff_bonuses.view_all')) $tabs['recap']='Rekap';
    $roles = collect(config('staff-bonuses.eligible_roles'))->mapWithKeys(fn($role)=>[$role=>config("rbac.roles.$role.label",$role)]);
    $statusTone = fn($status) => match($status instanceof \BackedEnum ? $status->value : $status){'active'=>'primary','pending_approval'=>'warning','approved'=>'success','closed'=>'info','rejected'=>'danger','paid'=>'success',default=>'secondary'};
@endphp

<div class="card mb-5 border border-gray-200 shadow-none"><div class="card-body py-3"><ul class="nav nav-pills gap-2">@foreach($tabs as $key=>$label)<li class="nav-item"><a href="{{ route('staff-bonuses.index',['tab'=>$key]) }}" class="nav-link {{ $tab===$key?'active':'' }}">{{ $label }}</a></li>@endforeach</ul></div></div>

@if($errors->any())<div class="alert alert-danger"><div class="fw-bold mb-2">Data belum dapat disimpan:</div><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

@if($tab==='mine')
    <div class="row g-4 mb-5">
        <div class="col-md-4"><div class="card bg-light-primary border-0 h-100"><div class="card-body"><div class="text-muted">Program Aktif</div><div class="fs-2 fw-bold text-primary">{{ $mine->where('period.status',\App\Enums\StaffBonusPeriodStatus::ACTIVE)->count() }}</div></div></div></div>
        <div class="col-md-4"><div class="card bg-light-success border-0 h-100"><div class="card-body"><div class="text-muted">Total Estimasi Bonus</div><div class="fs-2 fw-bold text-success">{{ \App\Support\CurrencyFormatter::rupiah($mine->sum('bonus_amount')) }}</div></div></div></div>
        <div class="col-md-4"><div class="card bg-light-info border-0 h-100"><div class="card-body"><div class="text-muted">Sudah Dibayar</div><div class="fs-2 fw-bold text-info">{{ $mine->where('payment_status','paid')->count() }}</div></div></div></div>
    </div>
    <x-metronic.card title="Target dan Bonus Saya" subtitle="Nilai dihitung dari data transaksi, absensi terverifikasi, dan checklist kerja.">
        @include('staff-bonuses.partials.results-table',['rows'=>$mine,'showUser'=>false])
        {{ $mine->links() }}
    </x-metronic.card>
    @if($legacy->isNotEmpty())<x-metronic.card class="mt-5" title="Histori Bonus Sales - Skema Lama" subtitle="Data ini dipertahankan sesuai nilai yang telah dihitung oleh sistem lama."><div class="table-responsive"><table class="table table-row-dashed align-middle"><thead><tr><th>Periode</th><th>Sales</th><th>Penjualan</th><th>Target</th><th>Bonus</th><th>Status</th></tr></thead><tbody>@foreach($legacy as $row)<tr><td>{{ sprintf('%02d/%04d',$row->month,$row->year) }}</td><td>{{ $row->sales?->name }}</td><td>{{ \App\Support\CurrencyFormatter::rupiah($row->sales_amount) }}</td><td>{{ \App\Support\CurrencyFormatter::rupiah($row->target_amount) }}</td><td class="fw-bold">{{ \App\Support\CurrencyFormatter::rupiah($row->bonus_amount) }}</td><td><span class="badge badge-light-secondary">Skema Lama{{ $row->finalized_at?' · Terkunci':'' }}</span></td></tr>@endforeach</tbody></table></div></x-metronic.card>@endif
@endif

@if($tab==='team' && $canTeam)
    <x-metronic.card title="Kinerja Tim" subtitle="Kepala lokasi hanya melihat staf pada lokasi penugasannya.">
        @include('staff-bonuses.partials.filters',['targetTab'=>'team'])
        <div class="mt-5">@include('staff-bonuses.partials.results-table',['rows'=>$team,'showUser'=>true])</div>
        {{ $team?->links() }}
    </x-metronic.card>
@endif

@if($tab==='programs' && $canManage)
<div class="row g-5">
    <div class="col-xl-5"><x-metronic.card title="Buat Program Bulanan" subtitle="Program harus diaktifkan sebelum bulan target dimulai.">
        <form method="POST" action="{{ route('staff-bonuses.programs.store') }}" data-bonus-program-form>@csrf
            <div class="row g-4">
                <div class="col-md-5"><label class="form-label">Kode Program</label><input name="program_key" value="{{ old('program_key') }}" class="form-control form-control-solid" placeholder="TOKO-2026-10" required></div>
                <div class="col-md-7"><label class="form-label">Nama Program</label><input name="name" value="{{ old('name') }}" class="form-control form-control-solid" placeholder="Bonus Toko Oktober" required></div>
                <div class="col-md-6"><label class="form-label">Role</label><select name="role_name" class="form-select form-select-solid" data-bonus-role required><option value="">Pilih role</option>@foreach($roles as $key=>$label)<option value="{{ $key }}" @selected(old('role_name')===$key)>{{ $label }}</option>@endforeach</select></div>
                <div class="col-md-6"><label class="form-label">Lokasi</label><select name="work_location_id" class="form-select form-select-solid" data-bonus-location><option value="">Global (khusus Sales)</option>@foreach($locations as $location)<option value="{{ $location->id }}" data-type="{{ $location->type }}" @selected((string)old('work_location_id')===(string)$location->id)>{{ $location->name }}</option>@endforeach</select></div>
                <div class="col-md-4"><label class="form-label">Bulan</label><input type="number" name="month" min="1" max="12" value="{{ old('month',now('Asia/Jakarta')->addMonth()->month) }}" class="form-control form-control-solid" required></div>
                <div class="col-md-4"><label class="form-label">Tahun</label><input type="number" name="year" min="2020" value="{{ old('year',now('Asia/Jakarta')->addMonth()->year) }}" class="form-control form-control-solid" required></div>
                <div class="col-md-4"><label class="form-label">Bonus Maksimum</label><input type="number" name="maximum_bonus_amount" min="1" step="0.01" value="{{ old('maximum_bonus_amount') }}" class="form-control form-control-solid" required></div>
                <div class="col-12"><label class="form-label">Penerima dan Override Opsional</label><div class="border rounded p-3 overflow-auto" style="max-height:280px" data-bonus-users>@foreach($eligibleUsers as $staff)<div class="row g-2 align-items-center mb-3" data-user-role="{{ $staff->roles->pluck('name')->implode(',') }}" data-user-location="{{ $staff->employee?->work_location_id }}"><div class="col-5"><label class="form-check form-check-custom form-check-solid"><input class="form-check-input" type="checkbox" name="user_ids[]" value="{{ $staff->id }}" @checked(in_array($staff->id,old('user_ids',[])))><span class="form-check-label"><span class="fw-semibold">{{ $staff->name }}</span><span class="text-muted fs-8 d-block">{{ $staff->employee?->workLocation?->name ?? 'Tanpa lokasi' }}</span></span></label><input type="hidden" name="user_overrides[{{ $loop->index }}][user_id]" value="{{ $staff->id }}"></div><div class="col-3"><input type="number" step="0.0001" min="0.0001" name="user_overrides[{{ $loop->index }}][target_override]" class="form-control form-control-sm" placeholder="Target khusus"></div><div class="col-4"><input type="number" step="0.01" min="0.01" name="user_overrides[{{ $loop->index }}][maximum_bonus_override]" class="form-control form-control-sm" placeholder="Bonus maks. khusus"></div></div>@endforeach</div><div class="text-muted fs-8 mt-2">Kosongkan override untuk memakai target dan bonus program.</div></div>
                <div class="col-12"><label class="form-label">KPI dan Bobot</label><div class="d-flex flex-column gap-3">@foreach(config('staff-bonuses.metrics') as $key=>$metric)@php $defaults=['warehouse_tasks'=>40,'warehouse_accuracy'=>20,'pos_net_sales'=>50,'cash_accuracy'=>10,'b2b_net_sales'=>80,'attendance_rate'=>20,'checklist_on_time'=>20]; @endphp<div class="border rounded p-3" data-metric-roles="{{ implode(',',$metric['roles']) }}"><input type="hidden" name="metrics[{{ $loop->index }}][metric_key]" value="{{ $key }}" disabled><div class="fw-semibold mb-2">{{ $metric['label'] }} <span class="badge badge-light">{{ $metric['scope']==='team'?'Tim':'Individu' }}</span></div><div class="row g-2"><div class="col-7"><div class="input-group input-group-sm"><span class="input-group-text">Target</span><input type="number" step="0.0001" min="0.0001" name="metrics[{{ $loop->index }}][target_value]" class="form-control" value="{{ str_contains($key,'accuracy')||str_contains($key,'rate')||$key==='checklist_on_time'?100:'' }}" disabled required></div></div><div class="col-5"><div class="input-group input-group-sm"><input type="number" step="0.0001" min="0.0001" max="100" name="metrics[{{ $loop->index }}][weight_percentage]" class="form-control" value="{{ $defaults[$key] }}" disabled required><span class="input-group-text">%</span></div></div></div></div>@endforeach</div><div class="text-muted fs-8 mt-2">Total bobot KPI yang tampil wajib 100%.</div></div>
                <div class="col-12 text-end"><button class="btn btn-primary"><i class="ki-outline ki-plus fs-5"></i>Simpan Draft</button></div>
            </div>
        </form>
    </x-metronic.card></div>
    <div class="col-xl-7"><x-metronic.card title="Daftar Program"><div class="d-flex flex-column gap-3">@forelse($programs as $program)<div class="border rounded p-4"><div class="d-flex justify-content-between gap-3"><div><div class="fw-bold">{{ $program->name }}</div><div class="text-muted fs-8">{{ config("rbac.roles.{$program->role_name}.label",$program->role_name) }} · {{ $program->workLocation?->name ?? 'Global' }} · {{ sprintf('%02d/%04d',$program->month,$program->year) }}</div><div class="mt-2"><span class="badge badge-light-{{ $statusTone($program->status) }}">{{ $program->status->label() }}</span> <span class="badge badge-light-primary">{{ $program->metrics->count() }} KPI</span> <span class="badge badge-light-info">{{ $program->assignments->count() }} staf</span></div><div class="mt-2">Bonus maksimum: <strong>{{ \App\Support\CurrencyFormatter::rupiah($program->maximum_bonus_amount) }}</strong></div></div><div class="d-flex flex-column gap-2">@if($program->status===\App\Enums\StaffBonusProgramStatus::DRAFT)<form method="POST" action="{{ route('staff-bonuses.programs.activate',$program) }}">@csrf<button class="btn btn-sm btn-success">Aktifkan</button></form>@elseif($program->period)<form method="POST" action="{{ route('staff-bonuses.periods.calculate',$program->period) }}">@csrf<button class="btn btn-sm btn-light-primary">Hitung Ulang</button></form><form method="POST" action="{{ route('staff-bonuses.periods.submit',$program->period) }}">@csrf<button class="btn btn-sm btn-warning" @disabled(!in_array($program->period->status,[\App\Enums\StaffBonusPeriodStatus::ACTIVE,\App\Enums\StaffBonusPeriodStatus::REJECTED],true))>Ajukan</button></form>@endif</div></div></div>@empty<x-metronic.empty-state title="Belum ada program" description="Buat program bonus untuk bulan berikutnya." />@endforelse</div>{{ $programs->links() }}</x-metronic.card></div>
</div>
@endif

@if($tab==='approval' && $canDecision)
    @forelse($pending as $period)<x-metronic.card class="mb-5" :title="$period->program->name" :subtitle="sprintf('%02d/%04d · %s',$period->month,$period->year,$period->workLocation?->name??'Global')"><div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><span class="badge badge-light-{{ $statusTone($period->status) }}">{{ $period->status->label() }}</span><div class="fs-2 fw-bold mt-2">{{ \App\Support\CurrencyFormatter::rupiah($period->total_bonus_amount) }}</div><div class="text-muted fs-8">{{ $period->results->count() }} penerima</div></div>@if($period->status===\App\Enums\StaffBonusPeriodStatus::PENDING_APPROVAL && $period->approvalRequest && auth()->user()->can('approve', $period->approvalRequest))<div class="d-flex gap-2 align-items-start"><form method="POST" action="{{ route('staff-bonuses.periods.approve',$period) }}">@csrf<input name="note" class="form-control form-control-sm mb-2" placeholder="Catatan opsional"><button class="btn btn-success w-100">Setujui</button></form><form method="POST" action="{{ route('staff-bonuses.periods.reject',$period) }}">@csrf<input name="note" class="form-control form-control-sm mb-2" required minlength="5" placeholder="Alasan penolakan"><button class="btn btn-light-danger w-100">Tolak</button></form></div>@endif</div><div class="table-responsive"><table class="table table-row-dashed align-middle"><thead><tr><th>Staf</th><th>Nilai</th><th>Bonus</th><th>Pembayaran</th></tr></thead><tbody>@foreach($period->results as $result)<tr><td>{{ $result->user?->name }}</td><td>{{ number_format((float)$result->final_score,2,',','.') }}</td><td class="fw-bold">{{ \App\Support\CurrencyFormatter::rupiah($result->bonus_amount) }}</td><td>@if($result->payment)<span class="badge badge-light-success">Dibayar {{ $result->payment->paid_on->format('d/m/Y') }}</span>@elseif($period->status===\App\Enums\StaffBonusPeriodStatus::APPROVED && auth()->user()->can('staff_bonuses.pay'))<form method="POST" enctype="multipart/form-data" action="{{ route('staff-bonuses.results.pay',$result) }}" class="row g-2">@csrf<div class="col"><input type="date" name="paid_on" value="{{ now()->toDateString() }}" class="form-control form-control-sm" required></div><div class="col"><select name="payment_method" class="form-select form-select-sm"><option value="bank_transfer">Transfer Bank</option><option value="cash">Tunai</option><option value="e_wallet">Dompet Digital</option><option value="other">Lainnya</option></select></div><div class="col"><input name="reference_no" class="form-control form-control-sm" placeholder="Referensi" required></div><div class="col-auto"><button class="btn btn-sm btn-primary">Catat Bayar</button></div></form>@else<span class="badge badge-light-warning">Belum Dibayar</span>@endif</td></tr>@endforeach</tbody></table></div></x-metronic.card>@empty<x-metronic.empty-state title="Tidak ada proses persetujuan" description="Periode yang diajukan atau disetujui akan muncul di sini." />@endforelse
@endif

@if($tab==='recap' && auth()->user()->can('staff_bonuses.view_all'))
    <div class="row g-4 mb-5"><div class="col-md-4"><div class="card bg-light-primary border-0"><div class="card-body"><div class="text-muted">Penerima</div><div class="fs-2 fw-bold text-primary">{{ number_format($recapSummary['recipients'],0,',','.') }}</div></div></div></div><div class="col-md-4"><div class="card bg-light-success border-0"><div class="card-body"><div class="text-muted">Bonus Disetujui</div><div class="fs-2 fw-bold text-success">{{ \App\Support\CurrencyFormatter::rupiah($recapSummary['approved_amount']) }}</div></div></div></div><div class="col-md-4"><div class="card bg-light-info border-0"><div class="card-body"><div class="text-muted">Sudah Dibayar</div><div class="fs-2 fw-bold text-info">{{ \App\Support\CurrencyFormatter::rupiah($recapSummary['paid_amount']) }}</div></div></div></div></div>
    <x-metronic.card title="Rekap Bonus"><div class="d-flex justify-content-between align-items-start gap-3">@include('staff-bonuses.partials.filters',['targetTab'=>'recap'])<a href="{{ route('staff-bonuses.export',request()->except('tab')) }}" class="btn btn-light-success">Unduh CSV</a></div><div class="mt-5">@include('staff-bonuses.partials.results-table',['rows'=>$team,'showUser'=>true])</div>{{ $team?->links() }}</x-metronic.card>
@endif

@if($selected)<div class="card mt-5 border border-primary"><div class="card-header"><h3 class="card-title">Rincian Nilai: {{ $selected->user?->name }}</h3></div><div class="card-body"><div class="table-responsive"><table class="table table-row-dashed"><thead><tr><th>KPI</th><th>Lingkup</th><th>Target</th><th>Aktual</th><th>Skor</th><th>Bobot</th><th>Nilai</th></tr></thead><tbody>@foreach($selected->metrics as $metric)<tr><td>{{ $metric->label }}</td><td>{{ $metric->scope==='team'?'Tim':'Individu' }}</td><td>{{ qty($metric->target_value) }}</td><td>{{ qty($metric->actual_value) }}</td><td>{{ number_format((float)$metric->score,2,',','.') }}</td><td>{{ number_format((float)$metric->weight_percentage,2,',','.') }}%</td><td class="fw-bold">{{ number_format((float)$metric->weighted_score,2,',','.') }}</td></tr>@endforeach</tbody></table></div>@if((float)$selected->adjustment_amount!==0.0)<div class="alert alert-info">Bonus hasil perhitungan {{ \App\Support\CurrencyFormatter::rupiah($selected->calculated_bonus_amount) }} dan penyesuaian {{ \App\Support\CurrencyFormatter::rupiah($selected->adjustment_amount) }}.</div>@endif @if($selected->payment_status==='paid' && auth()->user()->can('staff_bonuses.manage'))<div class="border rounded p-4 mt-4"><div class="fw-bold mb-3">Koreksi melalui periode berikutnya</div>@if($adjustmentTargets->isNotEmpty())<form method="POST" action="{{ route('staff-bonuses.results.adjust',$selected) }}" class="row g-3 align-items-end">@csrf<div class="col-md-4"><label class="form-label">Periode tujuan</label><select name="target_result_id" class="form-select" required>@foreach($adjustmentTargets as $target)<option value="{{ $target->id }}">{{ sprintf('%02d/%04d',$target->period->month,$target->period->year) }} · {{ $target->period->program->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Nilai penyesuaian</label><input type="number" step="0.01" name="amount" class="form-control" placeholder="Gunakan minus untuk potongan" required></div><div class="col-md-3"><label class="form-label">Alasan</label><input name="reason" class="form-control" minlength="10" required></div><div class="col-md-2"><button class="btn btn-warning w-100">Terapkan</button></div></form>@else<div class="text-muted">Belum ada periode berikutnya yang aktif untuk akun ini.</div>@endif</div>@endif</div></div>@endif

@push('scripts')
<script>document.addEventListener('DOMContentLoaded',()=>{const form=document.querySelector('[data-bonus-program-form]');if(!form)return;const role=form.querySelector('[data-bonus-role]'),location=form.querySelector('[data-bonus-location]');const refresh=()=>{const selected=role.value;form.querySelectorAll('[data-metric-roles]').forEach(row=>{const show=row.dataset.metricRoles.split(',').includes(selected);row.classList.toggle('d-none',!show);row.querySelectorAll('input').forEach(input=>input.disabled=!show)});form.querySelectorAll('[data-user-role]').forEach(row=>{const roleOk=row.dataset.userRole.split(',').includes(selected);const locationOk=selected==='sales'||!location.value||row.dataset.userLocation===location.value;row.classList.toggle('d-none',!(roleOk&&locationOk));if(!(roleOk&&locationOk))row.querySelector('input').checked=false});location.required=selected!=='sales'};role.addEventListener('change',refresh);location.addEventListener('change',refresh);refresh()});</script>
@endpush
@endsection
