@extends('layouts.metronic.app')
@section('title', 'Verifikasi, Dokumen, Harga dan Kredit')
@section('page_title', 'Verifikasi, Dokumen, Harga dan Kredit')
@section('content')
<form method="POST" enctype="multipart/form-data" action="{{ route('admin.customers.settings.update', $customer) }}">@csrf @method('PUT')
<x-metronic.card title="Status, Ring, dan Kredit">
    <div class="row"><div class="col-md-4"><x-metronic.form-group name="verification_status" label="Status Verifikasi"><select name="verification_status" class="form-select">@foreach($statuses as $value => $label)<option value="{{ $value }}" @selected(old('verification_status', $customer->verification_status->value) === $value)>{{ $label }}</option>@endforeach</select></x-metronic.form-group></div><div class="col-md-4"><x-metronic.form-group name="account_status" label="Status Akun"><select name="account_status" class="form-select">@foreach($statuses as $value => $label)<option value="{{ $value }}" @selected(old('account_status', $customer->account_status->value) === $value)>{{ $label }}</option>@endforeach</select></x-metronic.form-group></div><div class="col-md-4"><x-metronic.form-group name="price_category" label="Ring Harga"><select name="price_category" class="form-select">@foreach($priceCategories as $value => $label)<option value="{{ $value }}" @selected(old('price_category', $customer->price_category) === $value)>{{ $label }}</option>@endforeach</select></x-metronic.form-group></div><div class="col-md-4"><x-metronic.form-group name="minimum_order" label="Minimum Order"><input type="number" step="0.01" min="0" name="minimum_order" value="{{ old('minimum_order', $customer->minimum_order) }}" class="form-control"></x-metronic.form-group></div><div class="col-md-4"><x-metronic.form-group name="payment_term_days" label="Termin"><input type="number" min="0" max="365" name="payment_term_days" value="{{ old('payment_term_days', $customer->payment_term_days) }}" class="form-control"></x-metronic.form-group></div><div class="col-md-4"><x-metronic.form-group name="credit_limit" label="Limit Kredit"><input type="number" step="0.01" min="0" name="credit_limit" value="{{ old('credit_limit', $customer->credit_limit) }}" class="form-control"></x-metronic.form-group></div></div>
    <x-metronic.form-group name="status_reason" label="Alasan Perubahan / Freeze / Blacklist"><textarea name="status_reason" rows="3" class="form-control">{{ old('status_reason', $customer->status_reason) }}</textarea></x-metronic.form-group>
</x-metronic.card>
<x-metronic.card title="Dokumen Usaha" class="mt-6"><div class="row"><div class="col-md-4"><x-metronic.form-group name="document_type" label="Tipe Dokumen"><input name="document_type" value="{{ old('document_type') }}" class="form-control" placeholder="npwp/nib/ktp"></x-metronic.form-group></div><div class="col-md-4"><x-metronic.form-group name="document_name" label="Nama Dokumen"><input name="document_name" value="{{ old('document_name') }}" class="form-control"></x-metronic.form-group></div><div class="col-md-4"><x-metronic.form-group name="document" label="File"><input type="file" name="document" class="form-control" accept=".pdf,.jpg,.jpeg,.png"></x-metronic.form-group></div></div>@forelse($customer->documents as $document)<div>{{ $document->name }} · {{ $document->type }}</div>@empty<div class="text-muted">Belum ada dokumen.</div>@endforelse</x-metronic.card>
<x-metronic.card title="Harga Khusus Per Produk" class="mt-6"><div class="row"><div class="col-md-4"><x-metronic.form-group name="price_overrides.0.product_id" label="Produk"><select name="price_overrides[0][product_id]" class="form-select"><option value="">Pilih produk</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->sku }} · {{ $product->name }}</option>@endforeach</select></x-metronic.form-group></div><div class="col-md-2"><x-metronic.form-group name="price_overrides.0.price" label="Harga"><input type="number" step="0.01" min="0" name="price_overrides[0][price]" class="form-control"></x-metronic.form-group></div><div class="col-md-2"><x-metronic.form-group name="price_overrides.0.starts_at" label="Mulai"><input type="date" name="price_overrides[0][starts_at]" class="form-control"></x-metronic.form-group></div><div class="col-md-2"><x-metronic.form-group name="price_overrides.0.ends_at" label="Selesai"><input type="date" name="price_overrides[0][ends_at]" class="form-control"></x-metronic.form-group></div><div class="col-md-2"><x-metronic.form-group name="price_overrides.0.notes" label="Catatan"><input name="price_overrides[0][notes]" class="form-control"></x-metronic.form-group></div></div><table class="table"><thead><tr><th>Produk</th><th>Harga</th><th>Periode</th><th>Status</th></tr></thead><tbody>@forelse($customer->priceOverrides as $override)<tr><td>{{ $override->product?->name }}</td><td>{{ App\Support\CurrencyFormatter::rupiah($override->price) }}</td><td>{{ $override->starts_at?->format('d/m/Y') }} - {{ $override->ends_at?->format('d/m/Y') ?: 'seterusnya' }}</td><td>{{ $override->is_active ? 'Aktif' : 'Nonaktif' }}</td></tr>@empty<tr><td colspan="4">Belum ada harga khusus.</td></tr>@endforelse</tbody></table></x-metronic.card>
<div class="d-flex justify-content-end gap-3 mt-6"><a href="{{ route('admin.customers.show', $customer) }}" class="btn btn-light">Kembali</a><button class="btn btn-primary">Simpan Pengaturan</button></div>
</form>
@endsection
