<?php

return [
    [
        'label' => 'Dashboard',
        'icon' => 'ki-outline ki-home-2',
        'route' => 'dashboard',
        'active' => ['dashboard'],
        'permission' => 'dashboard.view',
    ],
    [
        'label' => 'Dashboard Owner',
        'icon' => 'ki-outline ki-chart-line-up',
        'route' => 'owner.dashboard',
        'active' => ['owner.dashboard'],
        'permission' => 'reports.view',
    ],
    [
        'label' => 'Administrasi',
        'icon' => 'ki-outline ki-security-user',
        'children' => [
            [
                'label' => 'Pengguna',
                'route' => 'admin.users.index',
                'active' => ['admin.users.*'],
                'permission' => 'admin.users.view',
            ],
            [
                'label' => 'Role',
                'route' => 'admin.roles.index',
                'active' => ['admin.roles.*'],
                'permission' => 'admin.roles.view',
            ],
            [
                'label' => 'Permission',
                'route' => 'admin.permissions.index',
                'active' => ['admin.permissions.*'],
                'permission' => 'admin.permissions.view',
            ],
        ],
    ],
    [
        'label' => 'Administrasi Sistem',
        'icon' => 'ki-outline ki-setting-2',
        'children' => [
            [
                'label' => 'Gudang',
                'route' => 'admin.warehouses.index',
                'active' => ['admin.warehouses.*'],
                'permission' => 'admin.warehouses.view',
            ],
            [
                'label' => 'Cabang/Toko',
                'route' => 'admin.branches.index',
                'active' => ['admin.branches.*'],
                'permission' => 'admin.branches.view',
            ],
            [
                'label' => 'Pengaturan Umum',
                'route' => 'admin.settings.general.edit',
                'active' => ['admin.settings.general.*'],
                'permission' => 'admin.settings.view',
            ],
            [
                'label' => 'Nomor Dokumen',
                'route' => 'admin.settings.document-numbers.index',
                'active' => ['admin.settings.document-numbers.*'],
                'permission' => 'admin.settings.view',
            ],
            [
                'label' => 'Kesehatan Sistem',
                'route' => 'system.health',
                'active' => ['system.health'],
                'permission' => 'system.health.view',
            ],
        ],
    ],
    [
        'label' => 'Master Produk',
        'icon' => 'ki-outline ki-parcel',
        'children' => [
            [
                'label' => 'Kategori Produk',
                'route' => 'admin.product-categories.index',
                'active' => ['admin.product-categories.*'],
                'permission' => 'products.view',
            ],
            [
                'label' => 'Merek Produk',
                'route' => 'admin.product-brands.index',
                'active' => ['admin.product-brands.*'],
                'permission' => 'products.view',
            ],
            [
                'label' => 'Satuan',
                'route' => 'admin.units.index',
                'active' => ['admin.units.*'],
                'permission' => 'products.view',
            ],
            [
                'label' => 'Produk',
                'route' => 'admin.products.index',
                'active' => ['admin.products.*'],
                'permission' => 'products.view',
            ],
            [
                'label' => 'Cetak Barcode/QR',
                'route' => 'admin.products.barcodes.index',
                'active' => ['admin.products.barcodes.*'],
                'permission' => 'products.print_barcode',
            ],
            [
                'label' => 'Import Produk',
                'route' => 'admin.products.import.index',
                'active' => ['admin.products.import.*'],
                'permission' => 'products.import',
            ],
        ],
    ],
    [
        'label' => 'Relasi Bisnis',
        'icon' => 'ki-outline ki-people',
        'children' => [
            [
                'label' => 'Supplier',
                'route' => 'admin.suppliers.index',
                'active' => ['admin.suppliers.*'],
                'permission' => 'suppliers.view',
            ],
            [
                'label' => 'Pelanggan & B2B',
                'route' => 'admin.customers.index',
                'active' => ['admin.customers.*'],
                'permission' => 'customers.view',
            ],
        ],
    ],
    [
        'label' => 'Gudang & Stok',
        'icon' => 'ki-outline ki-delivery-3',
        'children' => [
            [
                'label' => 'Dashboard Gudang',
                'route' => 'warehouse.dashboard',
                'active' => ['warehouse.dashboard'],
                'permission' => 'stock.view',
            ],
            [
                'label' => 'Zona, Rak, dan Bin',
                'route' => 'warehouse.locations.index',
                'active' => ['warehouse.locations.*'],
                'permission' => 'stock.view',
            ],
            [
                'label' => 'Saldo Stok',
                'route' => 'warehouse.stocks.index',
                'active' => ['warehouse.stocks.*'],
                'permission' => 'stock.view',
            ],
            [
                'label' => 'Kartu Stok',
                'route' => 'warehouse.stock-card.index',
                'active' => ['warehouse.stock-card.*'],
                'permission' => 'stock.view',
            ],
            [
                'label' => 'Penerimaan Barang',
                'route' => 'warehouse.goods-receipts.index',
                'active' => ['warehouse.goods-receipts.*'],
                'permission' => 'goods_receipts.view',
            ],
            [
                'label' => 'Order B2B Gudang',
                'route' => 'warehouse.b2b-orders.index',
                'active' => ['warehouse.b2b-orders.*'],
                'permission' => 'b2b_orders.view',
            ],
            [
                'label' => 'Reserved Stock',
                'route' => 'warehouse.reservations.index',
                'active' => ['warehouse.reservations.*'],
                'permission' => 'b2b_orders.view',
            ],
            [
                'label' => 'Pengiriman B2B',
                'route' => 'shipments.index',
                'active' => ['shipments.*'],
                'permission' => 'shipments.view',
            ],
            [
                'label' => 'Transfer Lokasi',
                'route' => 'warehouse.location-transfers.index',
                'active' => ['warehouse.location-transfers.*'],
                'permission' => 'stock_transfers.view',
            ],
            [
                'label' => 'Transfer Stok',
                'route' => 'warehouse.stock-transfers.index',
                'active' => ['warehouse.stock-transfers.*', 'retail.stock-transfers.*'],
                'permission' => 'stock_transfers.view',
            ],
            [
                'label' => 'Stok Opname',
                'route' => 'warehouse.stock-opnames.index',
                'active' => ['warehouse.stock-opnames.*'],
                'permission' => 'stock_adjustments.view',
            ],
            [
                'label' => 'Barang Rusak & Loss',
                'route' => 'warehouse.losses.index',
                'active' => ['warehouse.losses.*'],
                'permission' => 'losses.view',
            ],
            [
                'label' => 'Batch/Lot Stok',
                'route' => 'warehouse.batches.index',
                'active' => ['warehouse.batches.*'],
                'permission' => 'stock.view',
            ],
            [
                'label' => 'Histori HPP',
                'route' => 'pricing.hpp-history.index',
                'active' => ['pricing.hpp-history.*'],
                'permission' => 'goods_receipts.view',
            ],
        ],
    ],
    [
        'label' => 'Pembelian',
        'icon' => 'ki-outline ki-purchase',
        'children' => [
            [
                'label' => 'Permintaan Pembelian',
                'route' => 'purchasing.requests.index',
                'active' => ['purchasing.requests.*'],
                'permission' => 'purchase_orders.view',
            ],
            [
                'label' => 'Purchase Order',
                'route' => 'purchasing.purchase-orders.index',
                'active' => ['purchasing.purchase-orders.*'],
                'permission' => 'purchase_orders.view',
            ],
            [
                'label' => 'Performa Supplier',
                'route' => 'reports.suppliers.index',
                'active' => ['reports.suppliers.*'],
                'permission' => 'reports.view',
            ],
            [
                'label' => 'Laporan Loss',
                'route' => 'reports.losses.index',
                'active' => ['reports.losses.*'],
                'permission' => 'losses.view',
            ],
        ],
    ],
    [
        'label' => 'Harga & Margin',
        'icon' => 'ki-outline ki-price-tag',
        'children' => [
            [
                'label' => 'Aturan Harga',
                'route' => 'pricing.rules.index',
                'active' => ['pricing.rules.*'],
                'permission' => 'prices.view',
            ],
            [
                'label' => 'Harga Produk',
                'route' => 'pricing.product-prices.index',
                'active' => ['pricing.product-prices.*'],
                'permission' => 'prices.view',
            ],
            [
                'label' => 'Harga Khusus',
                'route' => 'pricing.special-prices.index',
                'active' => ['pricing.special-prices.*'],
                'permission' => 'prices.view',
            ],
            [
                'label' => 'Histori Harga',
                'route' => 'pricing.history.index',
                'active' => ['pricing.history.*'],
                'permission' => 'prices.view',
            ],
            [
                'label' => 'Approval Harga',
                'route' => 'pricing.approvals.index',
                'active' => ['pricing.approvals.*'],
                'permission' => 'prices.approve',
            ],
            [
                'label' => 'Simulasi Margin',
                'route' => 'pricing.simulator.index',
                'active' => ['pricing.simulator.*'],
                'permission' => 'prices.view',
            ],
        ],
    ],
    [
        'label' => 'Retur',
        'icon' => 'ki-outline ki-arrow-left-right',
        'children' => [
            [
                'label' => 'Daftar Retur',
                'route' => 'returns.index',
                'active' => ['returns.*'],
                'permission' => 'returns.view',
            ],
        ],
    ],
    [
        'label' => 'Toko Internal',
        'icon' => 'ki-outline ki-shop',
        'children' => [
            [
                'label' => 'Dashboard Cabang',
                'route' => 'retail.dashboard',
                'active' => ['retail.dashboard'],
                'permission' => 'cash_shifts.view',
            ],
            [
                'label' => 'Kasir POS',
                'route' => 'retail.pos.index',
                'active' => ['retail.pos.*'],
                'permission' => 'pos.view',
            ],
            [
                'label' => 'Shift Aktif',
                'route' => 'retail.shifts.current',
                'active' => ['retail.shifts.current', 'retail.shifts.open', 'retail.shifts.close', 'retail.shifts.expenses'],
                'permission' => 'cash_shifts.view',
            ],
            [
                'label' => 'Riwayat Shift',
                'route' => 'retail.shifts.index',
                'active' => ['retail.shifts.index', 'retail.shifts.approval'],
                'permission' => 'cash_shifts.view',
            ],
            [
                'label' => 'Transaksi Ditahan',
                'route' => 'retail.pos.holds',
                'active' => ['retail.pos.holds*'],
                'permission' => 'pos.create',
            ],
            [
                'label' => 'Permintaan Restock',
                'route' => 'retail.restock-requests.index',
                'active' => ['retail.restock-requests.*'],
                'permission' => 'stock_transfers.create',
            ],
            [
                'label' => 'Terima Transfer',
                'route' => 'warehouse.stock-transfers.index',
                'active' => ['retail.stock-transfers.*'],
                'permission' => 'stock_transfers.receive',
            ],
        ],
    ],
    [
        'label' => 'Kehadiran',
        'icon' => 'ki-outline ki-calendar-tick',
        'children' => [
            [
                'label' => 'Master Karyawan',
                'route' => 'attendance.employees.index',
                'active' => ['attendance.employees.*'],
                'permission' => 'attendance.view',
            ],
            [
                'label' => 'Master Shift',
                'route' => 'attendance.work-shifts.index',
                'active' => ['attendance.work-shifts.*'],
                'permission' => 'attendance.view',
            ],
            [
                'label' => 'Jadwal Shift',
                'route' => 'attendance.schedules.index',
                'active' => ['attendance.schedules.*'],
                'permission' => 'attendance.view',
            ],
            [
                'label' => 'Check-in/out',
                'route' => 'attendance.check.show',
                'active' => ['attendance.check.*'],
                'permission' => 'attendance.check',
            ],
            [
                'label' => 'Izin/Sakit/Cuti',
                'route' => 'attendance.requests.index',
                'active' => ['attendance.requests.*'],
                'permission' => 'attendance.check',
            ],
            [
                'label' => 'Koreksi Absensi',
                'route' => 'attendance.corrections.index',
                'active' => ['attendance.corrections.*'],
                'permission' => 'attendance.update',
            ],
            [
                'label' => 'Laporan Kehadiran',
                'route' => 'reports.attendance.index',
                'active' => ['reports.attendance.*'],
                'permission' => 'attendance.view',
            ],
            [
                'label' => 'Produktivitas Shift',
                'route' => 'reports.shift-productivity.index',
                'active' => ['reports.shift-productivity.*'],
                'permission' => 'attendance.view',
            ],
        ],
    ],
    [
        'label' => 'Kontrol & Audit',
        'icon' => 'ki-outline ki-shield-tick',
        'children' => [
            [
                'label' => 'Kotak Masuk Approval',
                'route' => 'approvals.index',
                'active' => ['approvals.*'],
                'permission' => 'approvals.view',
            ],
            [
                'label' => 'Audit Log',
                'route' => 'audit-logs.index',
                'active' => ['audit-logs.*'],
                'permission' => 'audit.view',
            ],
            [
                'label' => 'Dashboard Anomali',
                'route' => 'audit.anomalies.index',
                'active' => ['audit.anomalies.*'],
                'permission' => 'audit.view',
            ],
            [
                'label' => 'Log Login & Keamanan',
                'route' => 'audit.security.index',
                'active' => ['audit.security.*'],
                'permission' => 'audit.view',
            ],
            [
                'label' => 'Channel Notifikasi',
                'route' => 'admin.notifications.channels.index',
                'active' => ['admin.notifications.channels.*'],
                'permission' => 'notifications.view',
            ],
            [
                'label' => 'Template Pesan',
                'route' => 'admin.notifications.templates.index',
                'active' => ['admin.notifications.templates.*'],
                'permission' => 'notifications.view',
            ],
            [
                'label' => 'Jadwal Notifikasi',
                'route' => 'admin.notifications.schedules.index',
                'active' => ['admin.notifications.schedules.*'],
                'permission' => 'notifications.view',
            ],
            [
                'label' => 'Penerima Notifikasi',
                'route' => 'admin.notifications.recipients.index',
                'active' => ['admin.notifications.recipients.*'],
                'permission' => 'notifications.view',
            ],
            [
                'label' => 'Log Pengiriman',
                'route' => 'admin.notifications.logs.index',
                'active' => ['admin.notifications.logs.*'],
                'permission' => 'notifications.view',
            ],
            [
                'label' => 'Aturan Alert',
                'route' => 'admin.notifications.alerts.index',
                'active' => ['admin.notifications.alerts.*'],
                'permission' => 'notifications.view',
            ],
        ],
    ],
    [
        'label' => 'Invoice & Pembayaran',
        'icon' => 'ki-outline ki-bill',
        'children' => [
            [
                'label' => 'Dashboard Piutang',
                'route' => 'receivables.dashboard',
                'active' => ['receivables.dashboard'],
                'permission' => 'receivables.view',
            ],
            [
                'label' => 'Daftar Piutang',
                'route' => 'receivables.index',
                'active' => ['receivables.index', 'receivables.customers.*', 'receivables.adjustments'],
                'permission' => 'receivables.view',
            ],
            [
                'label' => 'Invoice',
                'route' => 'invoices.index',
                'active' => ['invoices.*'],
                'permission' => 'invoices.view',
            ],
            [
                'label' => 'Pembayaran Piutang',
                'route' => 'receivables.payments.create',
                'active' => ['receivables.payments.*', 'payments.*'],
                'permission' => 'receivables.pay',
            ],
            [
                'label' => 'Reminder Tagihan',
                'route' => 'receivables.reminders',
                'active' => ['receivables.reminders'],
                'permission' => 'receivables.view',
            ],
            [
                'label' => 'Limit Kredit',
                'route' => 'receivables.credit-limits',
                'active' => ['receivables.credit-limits'],
                'permission' => 'receivables.manage_limits',
            ],
            [
                'label' => 'Piutang Toko',
                'route' => 'retail.receivables.index',
                'active' => ['retail.receivables.*'],
                'permission' => 'receivables.view',
            ],
        ],
    ],
    [
        'label' => 'Laporan',
        'icon' => 'ki-outline ki-chart-pie-4',
        'children' => [
            [
                'label' => 'Harian Owner',
                'route' => 'reports.daily.index',
                'active' => ['reports.daily.*'],
                'permission' => 'reports.view',
            ],
            [
                'label' => 'Gudang',
                'route' => 'reports.warehouse.index',
                'active' => ['reports.warehouse.*'],
                'permission' => 'stock.view',
            ],
            [
                'label' => 'Toko',
                'route' => 'reports.retail.index',
                'active' => ['reports.retail.*'],
                'permission' => 'cash_shifts.view',
            ],
            [
                'label' => 'Langganan/B2B',
                'route' => 'reports.b2b.index',
                'active' => ['reports.b2b.*'],
                'permission' => 'b2b_orders.view',
            ],
            [
                'label' => 'Harga & Margin',
                'route' => 'reports.pricing.index',
                'active' => ['reports.pricing.*'],
                'permission' => 'prices.view',
            ],
            [
                'label' => 'Supplier',
                'route' => 'reports.suppliers.index',
                'active' => ['reports.suppliers.*'],
                'permission' => 'suppliers.view',
            ],
            [
                'label' => 'Kehadiran',
                'route' => 'reports.attendance.index',
                'active' => ['reports.attendance.*'],
                'permission' => 'attendance.view',
            ],
            [
                'label' => 'Piutang',
                'route' => 'reports.receivables.index',
                'active' => ['reports.receivables.*'],
                'permission' => 'receivables.view',
            ],
            [
                'label' => 'Audit & Notifikasi',
                'route' => 'reports.audit-notifications.index',
                'active' => ['reports.audit-notifications.*'],
                'permission' => 'audit.view',
            ],
            [
                'label' => 'Pusat Export',
                'route' => 'reports.exports.index',
                'active' => ['reports.exports.*'],
                'permission' => 'reports.export',
            ],
        ],
    ],
    [
        'label' => 'Portal Langganan',
        'icon' => 'ki-outline ki-basket',
        'children' => [
            [
                'label' => 'Dashboard Langganan',
                'route' => 'langganan.dashboard',
                'active' => ['langganan.dashboard'],
                'permission' => 'dashboard.view',
            ],
            [
                'label' => 'Katalog',
                'route' => 'langganan.katalog.index',
                'active' => ['langganan.katalog.*'],
                'permission' => 'b2b_orders.view',
            ],
            [
                'label' => 'Keranjang',
                'route' => 'langganan.keranjang.index',
                'active' => ['langganan.keranjang.*'],
                'permission' => 'b2b_orders.create',
            ],
            [
                'label' => 'Checkout',
                'route' => 'langganan.checkout.show',
                'active' => ['langganan.checkout.*'],
                'permission' => 'b2b_orders.create',
            ],
            [
                'label' => 'Reorder Cepat',
                'route' => 'langganan.reorder.index',
                'active' => ['langganan.reorder.*'],
                'permission' => 'b2b_orders.create',
            ],
            [
                'label' => 'Riwayat Order',
                'route' => 'langganan.orders.index',
                'active' => ['langganan.orders.*'],
                'permission' => 'b2b_orders.view',
            ],
            [
                'label' => 'Invoice',
                'route' => 'invoices.index',
                'active' => ['invoices.*'],
                'permission' => 'receivables.view',
            ],
            [
                'label' => 'Komplain',
                'route' => 'langganan.complaints.index',
                'active' => ['langganan.complaints.*'],
                'permission' => 'complaints.create',
            ],
            [
                'label' => 'Profil Usaha',
                'route' => 'langganan.profil.edit',
                'active' => ['langganan.profil.*'],
                'permission' => 'customers.view_own',
            ],
        ],
    ],
];
