<?php

return [
    'actions' => ['view', 'view_own', 'view_team', 'view_all', 'create', 'update', 'update_own', 'manage', 'approve', 'void', 'export', 'view_sensitive'],

    'permissions' => [
        'dashboard.view' => ['label' => 'Lihat Dashboard', 'module' => 'dashboard', 'action' => 'view', 'description' => 'Mengakses dashboard sesuai role.'],
        'work_checklists.view_own' => ['label' => 'Lihat Checklist Sendiri', 'module' => 'work_checklists', 'action' => 'view_own', 'description' => 'Melihat checklist kerja milik akun sendiri.'],
        'work_checklists.update_own' => ['label' => 'Isi Checklist Sendiri', 'module' => 'work_checklists', 'action' => 'update_own', 'description' => 'Mengisi, menyelesaikan, dan mengoreksi checklist kerja milik akun sendiri.'],
        'work_checklists.view_team' => ['label' => 'Lihat Rekap Tim', 'module' => 'work_checklists', 'action' => 'view_team', 'description' => 'Melihat rekap checklist bawahan pada lokasi penugasan.'],
        'work_checklists.view_all' => ['label' => 'Lihat Seluruh Rekap Checklist', 'module' => 'work_checklists', 'action' => 'view_all', 'description' => 'Melihat rekap checklist seluruh akun dan lokasi.'],
        'work_checklists.manage_templates' => ['label' => 'Kelola Template Checklist', 'module' => 'work_checklists', 'action' => 'manage', 'description' => 'Membuat versi dan menonaktifkan template checklist.'],
        'work_checklists.export' => ['label' => 'Export Rekap Checklist', 'module' => 'work_checklists', 'action' => 'export', 'description' => 'Mengunduh rekap checklist sesuai lingkup akses.'],
        'retail.catalog.view' => ['label' => 'Lihat Etalase Toko', 'module' => 'retail.catalog', 'action' => 'view', 'description' => 'Melihat produk, stok, harga, dan lokasi pajang toko yang ditugaskan.'],
        'retail.catalog.manage' => ['label' => 'Atur Lokasi Pajang', 'module' => 'retail.catalog', 'action' => 'update', 'description' => 'Mengatur area, rak, dan tingkat pajang produk toko.'],
        'emergency_purchases.view' => ['label' => 'Lihat Pembelian Darurat', 'module' => 'emergency_purchases', 'action' => 'view', 'description' => 'Melihat pembelian darurat toko penugasan.'],
        'emergency_purchases.create' => ['label' => 'Ajukan Pembelian Darurat', 'module' => 'emergency_purchases', 'action' => 'create', 'description' => 'Mengonfirmasi stockout dan mengajukan pembelian darurat.'],
        'emergency_purchases.purchase' => ['label' => 'Catat Pembelian Darurat', 'module' => 'emergency_purchases', 'action' => 'update', 'description' => 'Mencatat barang, biaya, sumber dana, dan nota.'],
        'emergency_purchases.approve' => ['label' => 'Setujui Pembelian Darurat', 'module' => 'emergency_purchases', 'action' => 'approve', 'description' => 'Memutuskan permintaan pembelian darurat.'],
        'emergency_purchases.manage' => ['label' => 'Kelola Pembelian Darurat', 'module' => 'emergency_purchases', 'action' => 'update', 'description' => 'Mengelola pembatalan, retur pemasok, reimbursement, dan aturan.'],
        'emergency_reports.view' => ['label' => 'Lihat Laporan Darurat Toko', 'module' => 'emergency_reports', 'action' => 'view', 'description' => 'Melihat biaya, lost margin, dan stockout toko.'],
        'product_requests.view' => ['label' => 'Lihat Pengajuan Produk Toko', 'module' => 'product_requests', 'action' => 'view', 'description' => 'Melihat usulan produk baru dari toko.'],
        'product_requests.create' => ['label' => 'Ajukan Produk Toko', 'module' => 'product_requests', 'action' => 'create', 'description' => 'Mengusulkan produk baru dari toko untuk diperiksa master data.'],
        'product_requests.approve' => ['label' => 'Periksa Pengajuan Produk Toko', 'module' => 'product_requests', 'action' => 'approve', 'description' => 'Menyetujui atau menolak usulan produk dan membuat master produk.'],
        'admin.users.view' => ['label' => 'Lihat Pengguna', 'module' => 'admin.users', 'action' => 'view', 'description' => 'Melihat daftar dan detail pengguna.'],
        'admin.users.create' => ['label' => 'Tambah Pengguna', 'module' => 'admin.users', 'action' => 'create', 'description' => 'Membuat akun pengguna baru.'],
        'admin.users.update' => ['label' => 'Ubah Pengguna', 'module' => 'admin.users', 'action' => 'update', 'description' => 'Mengubah profil, status, dan role pengguna.'],
        'admin.users.assign_locations' => ['label' => 'Atur Lokasi Pengguna', 'module' => 'admin.users', 'action' => 'update', 'description' => 'Menugaskan lokasi kerja pengguna.'],
        'admin.users.reset_password' => ['label' => 'Reset Password Pengguna', 'module' => 'admin.users', 'action' => 'update', 'description' => 'Mengirim link reset password pengguna.'],
        'admin.users.export' => ['label' => 'Export Pengguna', 'module' => 'admin.users', 'action' => 'export', 'description' => 'Mengunduh daftar pengguna.'],
        'admin.roles.view' => ['label' => 'Lihat Role', 'module' => 'admin.roles', 'action' => 'view', 'description' => 'Melihat role dan matriks permission.'],
        'admin.roles.create' => ['label' => 'Tambah Role', 'module' => 'admin.roles', 'action' => 'create', 'description' => 'Membuat role baru.'],
        'admin.roles.update' => ['label' => 'Ubah Role', 'module' => 'admin.roles', 'action' => 'update', 'description' => 'Mengubah metadata role dan permission.'],
        'admin.permissions.view' => ['label' => 'Lihat Permission', 'module' => 'admin.permissions', 'action' => 'view', 'description' => 'Melihat daftar permission sistem.'],
        'admin.warehouses.view' => ['label' => 'Lihat Gudang', 'module' => 'admin.warehouses', 'action' => 'view', 'description' => 'Melihat daftar dan detail gudang.'],
        'admin.warehouses.create' => ['label' => 'Tambah Gudang', 'module' => 'admin.warehouses', 'action' => 'create', 'description' => 'Membuat master gudang.'],
        'admin.warehouses.update' => ['label' => 'Ubah Gudang', 'module' => 'admin.warehouses', 'action' => 'update', 'description' => 'Mengubah master gudang dan status aktif.'],
        'admin.branches.view' => ['label' => 'Lihat Cabang/Toko', 'module' => 'admin.branches', 'action' => 'view', 'description' => 'Melihat daftar dan detail cabang/toko.'],
        'admin.branches.create' => ['label' => 'Tambah Cabang/Toko', 'module' => 'admin.branches', 'action' => 'create', 'description' => 'Membuat master cabang/toko.'],
        'admin.branches.update' => ['label' => 'Ubah Cabang/Toko', 'module' => 'admin.branches', 'action' => 'update', 'description' => 'Mengubah master cabang/toko dan status aktif.'],
        'admin.settings.view' => ['label' => 'Lihat Pengaturan Sistem', 'module' => 'admin.settings', 'action' => 'view', 'description' => 'Melihat pengaturan umum dan nomor dokumen.'],
        'admin.settings.update' => ['label' => 'Ubah Pengaturan Sistem', 'module' => 'admin.settings', 'action' => 'update', 'description' => 'Mengubah pengaturan umum dan nomor dokumen.'],
        'system.health.view' => ['label' => 'Lihat Kesehatan Sistem', 'module' => 'system.health', 'action' => 'view', 'description' => 'Mengakses halaman health check.'],
        'system.operations.view' => ['label' => 'Lihat Operasional Sistem', 'module' => 'system.operations', 'action' => 'view', 'description' => 'Mengakses backup, log, import awal, dan maintenance.'],
        'system.operations.update' => ['label' => 'Kelola Operasional Sistem', 'module' => 'system.operations', 'action' => 'update', 'description' => 'Menjalankan backup, retry job, dan aksi maintenance terkontrol.'],
        'products.view' => ['label' => 'Lihat Produk', 'module' => 'products', 'action' => 'view', 'description' => 'Melihat master produk.'],
        'products.create' => ['label' => 'Tambah Produk', 'module' => 'products', 'action' => 'create', 'description' => 'Membuat master produk.'],
        'products.update' => ['label' => 'Ubah Produk', 'module' => 'products', 'action' => 'update', 'description' => 'Mengubah master produk.'],
        'products.import' => ['label' => 'Import Produk', 'module' => 'products', 'action' => 'create', 'description' => 'Mengimpor master produk dari Excel/CSV.'],
        'products.export' => ['label' => 'Export Produk', 'module' => 'products', 'action' => 'export', 'description' => 'Mengunduh master produk dan template import.'],
        'products.print_barcode' => ['label' => 'Cetak Barcode Produk', 'module' => 'products', 'action' => 'export', 'description' => 'Mencetak label barcode/QR produk.'],
        'suppliers.view' => ['label' => 'Lihat Supplier', 'module' => 'suppliers', 'action' => 'view', 'description' => 'Melihat master supplier.'],
        'suppliers.create' => ['label' => 'Tambah Supplier', 'module' => 'suppliers', 'action' => 'create', 'description' => 'Membuat master supplier.'],
        'suppliers.update' => ['label' => 'Ubah Supplier', 'module' => 'suppliers', 'action' => 'update', 'description' => 'Mengubah master supplier dan status aktif.'],
        'suppliers.import' => ['label' => 'Import Supplier', 'module' => 'suppliers', 'action' => 'create', 'description' => 'Mengimpor master supplier dari Excel/CSV.'],
        'suppliers.export' => ['label' => 'Export Supplier', 'module' => 'suppliers', 'action' => 'export', 'description' => 'Mengunduh master supplier.'],
        'customers.view' => ['label' => 'Lihat Pelanggan', 'module' => 'customers', 'action' => 'view', 'description' => 'Melihat master pelanggan.'],
        'customers.view_own' => ['label' => 'Lihat Pelanggan Sendiri', 'module' => 'customers', 'action' => 'view', 'description' => 'Melihat pelanggan B2B yang terhubung ke akun.'],
        'customers.create' => ['label' => 'Tambah Pelanggan', 'module' => 'customers', 'action' => 'create', 'description' => 'Membuat master pelanggan.'],
        'customers.update' => ['label' => 'Ubah Pelanggan', 'module' => 'customers', 'action' => 'update', 'description' => 'Mengubah master pelanggan dan status.'],
        'customers.manage_access' => ['label' => 'Kelola Akses B2B', 'module' => 'customers', 'action' => 'update', 'description' => 'Mengelola alamat kirim dan akun B2B pelanggan.'],
        'customers.manage_settings' => ['label' => 'Kelola Kredit dan Verifikasi', 'module' => 'customers', 'action' => 'approve', 'description' => 'Mengelola dokumen, status verifikasi, harga khusus, limit, dan termin.'],
        'customers.import' => ['label' => 'Import Pelanggan', 'module' => 'customers', 'action' => 'create', 'description' => 'Mengimpor master pelanggan dari Excel/CSV.'],
        'customers.export' => ['label' => 'Export Pelanggan', 'module' => 'customers', 'action' => 'export', 'description' => 'Mengunduh master pelanggan.'],
        'prices.view' => ['label' => 'Lihat Harga', 'module' => 'prices', 'action' => 'view', 'description' => 'Melihat daftar harga.'],
        'prices.update' => ['label' => 'Ubah Harga', 'module' => 'prices', 'action' => 'update', 'description' => 'Mengubah harga.'],
        'prices.approve' => ['label' => 'Approve Harga', 'module' => 'prices', 'action' => 'approve', 'description' => 'Menyetujui perubahan harga sensitif.'],
        'stock.view' => ['label' => 'Lihat Stok', 'module' => 'stock', 'action' => 'view', 'description' => 'Melihat stok lokasi.'],
        'stock.create' => ['label' => 'Buat Transaksi Stok', 'module' => 'stock', 'action' => 'create', 'description' => 'Membuat dokumen stok.'],
        'stock.update' => ['label' => 'Ubah Transaksi Stok', 'module' => 'stock', 'action' => 'update', 'description' => 'Mengubah dokumen stok draft.'],
        'stock_transfers.view' => ['label' => 'Lihat Transfer Stok', 'module' => 'stock_transfers', 'action' => 'view', 'description' => 'Melihat transfer stok.'],
        'stock_transfers.create' => ['label' => 'Buat Transfer Stok', 'module' => 'stock_transfers', 'action' => 'create', 'description' => 'Membuat transfer stok.'],
        'stock_transfers.approve' => ['label' => 'Approve Transfer Stok', 'module' => 'stock_transfers', 'action' => 'approve', 'description' => 'Menyetujui transfer stok.'],
        'stock_transfers.pack' => ['label' => 'Picking/Packing Transfer', 'module' => 'stock_transfers', 'action' => 'update', 'description' => 'Melakukan picking dan packing transfer stok.'],
        'stock_transfers.ship' => ['label' => 'Kirim Transfer Stok', 'module' => 'stock_transfers', 'action' => 'update', 'description' => 'Mengirim transfer stok.'],
        'stock_transfers.receive' => ['label' => 'Terima Transfer Stok', 'module' => 'stock_transfers', 'action' => 'create', 'description' => 'Mengonfirmasi penerimaan transfer di cabang.'],
        'stock_adjustments.view' => ['label' => 'Lihat Koreksi Stok', 'module' => 'stock_adjustments', 'action' => 'view', 'description' => 'Melihat koreksi stok.'],
        'stock_adjustments.create' => ['label' => 'Buat Koreksi Stok', 'module' => 'stock_adjustments', 'action' => 'create', 'description' => 'Membuat koreksi stok.'],
        'stock_adjustments.approve' => ['label' => 'Approve Koreksi Stok', 'module' => 'stock_adjustments', 'action' => 'approve', 'description' => 'Menyetujui koreksi stok.'],
        'returns.view' => ['label' => 'Lihat Retur', 'module' => 'returns', 'action' => 'view', 'description' => 'Melihat retur dan settlement.'],
        'returns.create' => ['label' => 'Buat Retur', 'module' => 'returns', 'action' => 'create', 'description' => 'Mengajukan retur.'],
        'returns.inspect' => ['label' => 'QC Retur', 'module' => 'returns', 'action' => 'update', 'description' => 'Melakukan pemeriksaan retur.'],
        'returns.approve' => ['label' => 'Approve Retur', 'module' => 'returns', 'action' => 'approve', 'description' => 'Menyetujui retur/loss bernilai besar.'],
        'returns.settle' => ['label' => 'Settlement Retur', 'module' => 'returns', 'action' => 'update', 'description' => 'Menyelesaikan refund, credit note, atau retur supplier.'],
        'losses.view' => ['label' => 'Lihat Loss', 'module' => 'losses', 'action' => 'view', 'description' => 'Melihat kerugian inventory.'],
        'losses.create' => ['label' => 'Catat Loss', 'module' => 'losses', 'action' => 'create', 'description' => 'Mencatat barang rusak/hilang.'],
        'purchase_orders.view' => ['label' => 'Lihat Purchase Order', 'module' => 'purchase_orders', 'action' => 'view', 'description' => 'Melihat PO pembelian.'],
        'purchase_orders.create' => ['label' => 'Buat Purchase Order', 'module' => 'purchase_orders', 'action' => 'create', 'description' => 'Membuat PO pembelian.'],
        'purchase_orders.approve' => ['label' => 'Approve Purchase Order', 'module' => 'purchase_orders', 'action' => 'approve', 'description' => 'Menyetujui PO pembelian.'],
        'purchase_orders.export' => ['label' => 'Export Purchase Order', 'module' => 'purchase_orders', 'action' => 'export', 'description' => 'Mengunduh daftar dan dokumen PO.'],
        'goods_receipts.view' => ['label' => 'Lihat Penerimaan Barang', 'module' => 'goods_receipts', 'action' => 'view', 'description' => 'Melihat penerimaan barang.'],
        'goods_receipts.create' => ['label' => 'Buat Penerimaan Barang', 'module' => 'goods_receipts', 'action' => 'create', 'description' => 'Mencatat penerimaan barang.'],
        'pos.view' => ['label' => 'Lihat POS', 'module' => 'pos', 'action' => 'view', 'description' => 'Mengakses transaksi POS.'],
        'pos.create' => ['label' => 'Buat Penjualan POS', 'module' => 'pos', 'action' => 'create', 'description' => 'Membuat penjualan POS.'],
        'pos.void' => ['label' => 'Void POS', 'module' => 'pos', 'action' => 'void', 'description' => 'Membatalkan transaksi POS dengan alasan.'],
        'cash_shifts.view' => ['label' => 'Lihat Shift Kas', 'module' => 'cash_shifts', 'action' => 'view', 'description' => 'Melihat shift kasir.'],
        'cash_shifts.create' => ['label' => 'Buka Shift Kas', 'module' => 'cash_shifts', 'action' => 'create', 'description' => 'Membuka shift kas.'],
        'cash_shifts.approve' => ['label' => 'Approve Closing Shift', 'module' => 'cash_shifts', 'action' => 'approve', 'description' => 'Menyetujui closing shift.'],
        'attendance.view' => ['label' => 'Lihat Kehadiran', 'module' => 'attendance', 'action' => 'view', 'description' => 'Melihat master, jadwal, absensi, dan laporan kehadiran.'],
        'attendance.check' => ['label' => 'Check-in/out Kehadiran', 'module' => 'attendance', 'action' => 'create', 'description' => 'Melakukan check-in, check-out, dan pengajuan izin/sakit/cuti.'],
        'attendance.update' => ['label' => 'Kelola Kehadiran', 'module' => 'attendance', 'action' => 'update', 'description' => 'Mengelola karyawan, shift, jadwal, dan koreksi absensi.'],
        'attendance.approve' => ['label' => 'Approve Kehadiran', 'module' => 'attendance', 'action' => 'approve', 'description' => 'Menyetujui izin, sakit, cuti, koreksi, dan override absensi.'],
        'attendance.export' => ['label' => 'Export Kehadiran', 'module' => 'attendance', 'action' => 'export', 'description' => 'Mengunduh laporan kehadiran dan produktivitas shift.'],
        'b2b_orders.view' => ['label' => 'Lihat Order B2B', 'module' => 'b2b_orders', 'action' => 'view', 'description' => 'Melihat order pelanggan langganan.'],
        'b2b_orders.create' => ['label' => 'Buat Order B2B', 'module' => 'b2b_orders', 'action' => 'create', 'description' => 'Membuat order B2B.'],
        'b2b_orders.approve' => ['label' => 'Approve Order B2B', 'module' => 'b2b_orders', 'action' => 'approve', 'description' => 'Menyetujui order B2B.'],
        'sales.dashboard.view' => ['label' => 'Lihat Dashboard Sales', 'module' => 'sales.dashboard', 'action' => 'view', 'description' => 'Melihat dashboard performa Sales sendiri.'],
        'sales.customers.view_own' => ['label' => 'Lihat Customer Sales Sendiri', 'module' => 'sales.customers', 'action' => 'view_own', 'description' => 'Melihat customer yang ditugaskan kepada Sales.'],
        'sales.orders.view_own' => ['label' => 'Lihat Order Sales Sendiri', 'module' => 'sales.orders', 'action' => 'view_own', 'description' => 'Melihat order yang menjadi tanggung jawab Sales.'],
        'sales.orders.create' => ['label' => 'Buat Order Sales', 'module' => 'sales.orders', 'action' => 'create', 'description' => 'Membuat order B2B untuk customer yang ditugaskan.'],
        'sales.stock.view' => ['label' => 'Cek Stok Sales', 'module' => 'sales.stock', 'action' => 'view', 'description' => 'Melihat available stock tanpa hak mutasi.'],
        'sales.targets.view_own' => ['label' => 'Lihat Target dan Bonus Sendiri', 'module' => 'sales.targets', 'action' => 'view_own', 'description' => 'Melihat target dan bonus Sales sendiri.'],
        'sales.performance.view' => ['label' => 'Lihat Performance Sales', 'module' => 'sales.performance', 'action' => 'view', 'description' => 'Melihat performance seluruh Sales.'],
        'sales.targets.manage' => ['label' => 'Kelola Target Sales', 'module' => 'sales.targets', 'action' => 'manage', 'description' => 'Menentukan target dan persentase bonus Sales.'],
        'staff_bonuses.view_own' => ['label' => 'Lihat Target dan Bonus Sendiri', 'module' => 'staff_bonuses', 'action' => 'view_own', 'description' => 'Melihat target, progres, dan bonus milik akun sendiri.'],
        'staff_bonuses.view_team' => ['label' => 'Lihat Bonus Tim', 'module' => 'staff_bonuses', 'action' => 'view_team', 'description' => 'Melihat target dan bonus tim pada lokasi penugasan.'],
        'staff_bonuses.view_all' => ['label' => 'Lihat Seluruh Bonus', 'module' => 'staff_bonuses', 'action' => 'view_all', 'description' => 'Melihat target dan bonus seluruh organisasi.'],
        'staff_bonuses.manage' => ['label' => 'Kelola Program Bonus', 'module' => 'staff_bonuses', 'action' => 'manage', 'description' => 'Membuat target dan mengaktifkan program bonus staf.'],
        'staff_bonuses.approve' => ['label' => 'Setujui Bonus', 'module' => 'staff_bonuses', 'action' => 'approve', 'description' => 'Menyetujui atau menolak hasil bonus staf.'],
        'staff_bonuses.pay' => ['label' => 'Catat Pembayaran Bonus', 'module' => 'staff_bonuses', 'action' => 'pay', 'description' => 'Mencatat pembayaran bonus yang telah disetujui.'],
        'staff_bonuses.export' => ['label' => 'Ekspor Rekap Bonus', 'module' => 'staff_bonuses', 'action' => 'export', 'description' => 'Mengunduh rekap target dan bonus staf.'],
        'sales.customers.assign' => ['label' => 'Assignment Customer Sales', 'module' => 'sales.customers', 'action' => 'assign', 'description' => 'Menentukan Sales penanggung jawab customer.'],
        'tax.access' => ['label' => 'Akses Pajak', 'module' => 'tax', 'action' => 'view', 'description' => 'Mengakses register, rekonsiliasi, dan laporan masa pajak.'],
        'tax.manage' => ['label' => 'Kelola Pajak', 'module' => 'tax', 'action' => 'manage', 'description' => 'Mengelola profil, aturan, klasifikasi, dan dokumen pajak.'],
        'tax.approve' => ['label' => 'Approve Masa Pajak', 'module' => 'tax', 'action' => 'approve', 'description' => 'Review, approve, laporkan, bayar, kunci, atau buka kembali masa pajak.'],
        'tax.export' => ['label' => 'Export Pajak', 'module' => 'tax', 'action' => 'export', 'description' => 'Mengekspor staging register pajak untuk rekonsiliasi Coretax.'],
        'finance_annual.view' => ['label' => 'Lihat Keuangan Tahunan', 'module' => 'finance_annual', 'action' => 'view', 'description' => 'Melihat rekap keuangan dan pajak tahunan.'],
        'finance_annual.manage' => ['label' => 'Kelola Keuangan Tahunan', 'module' => 'finance_annual', 'action' => 'manage', 'description' => 'Menyusun snapshot dan koreksi laporan keuangan.'],
        'finance_annual.approve' => ['label' => 'Setujui Keuangan Tahunan', 'module' => 'finance_annual', 'action' => 'approve', 'description' => 'Memeriksa, membuka, menyetujui, dan mengunci periode.'],
        'finance_annual.export' => ['label' => 'Ekspor Keuangan Tahunan', 'module' => 'finance_annual', 'action' => 'export', 'description' => 'Mengunduh laporan tahunan PDF dan Excel.'],
        'invoices.view' => ['label' => 'Lihat Invoice', 'module' => 'invoices', 'action' => 'view', 'description' => 'Melihat invoice dan PDF dokumen.'],
        'invoices.create' => ['label' => 'Terbitkan Invoice', 'module' => 'invoices', 'action' => 'create', 'description' => 'Menerbitkan invoice dari order B2B.'],
        'receivables.view' => ['label' => 'Lihat Piutang', 'module' => 'receivables', 'action' => 'view', 'description' => 'Melihat piutang pelanggan.'],
        'receivables.pay' => ['label' => 'Input Pembayaran Piutang', 'module' => 'receivables', 'action' => 'create', 'description' => 'Mencatat pembayaran dan alokasi piutang.'],
        'receivables.adjust' => ['label' => 'Buat Koreksi Piutang', 'module' => 'receivables', 'action' => 'update', 'description' => 'Membuat credit note/debit note piutang.'],
        'receivables.approve' => ['label' => 'Approve Koreksi Piutang', 'module' => 'receivables', 'action' => 'approve', 'description' => 'Menyetujui koreksi atau credit note piutang.'],
        'receivables.manage_limits' => ['label' => 'Kelola Limit Kredit', 'module' => 'receivables', 'action' => 'approve', 'description' => 'Mengelola limit, status blokir, dan aturan overdue pelanggan.'],
        'receivables.remind' => ['label' => 'Kelola Reminder Piutang', 'module' => 'receivables', 'action' => 'create', 'description' => 'Mencatat reminder dan follow-up penagihan.'],
        'receivables.export' => ['label' => 'Export Piutang', 'module' => 'receivables', 'action' => 'export', 'description' => 'Mengunduh laporan piutang dan aging.'],
        'payments.create' => ['label' => 'Input Pembayaran', 'module' => 'payments', 'action' => 'create', 'description' => 'Mencatat pembayaran.'],
        'payments.verify' => ['label' => 'Verifikasi Pembayaran', 'module' => 'payments', 'action' => 'approve', 'description' => 'Memverifikasi atau menolak bukti pembayaran.'],
        'shipments.view' => ['label' => 'Lihat Pengiriman', 'module' => 'shipments', 'action' => 'view', 'description' => 'Melihat daftar dan detail shipment.'],
        'shipments.create' => ['label' => 'Buat Pengiriman', 'module' => 'shipments', 'action' => 'create', 'description' => 'Membuat shipment B2B.'],
        'shipments.update' => ['label' => 'Update Pengiriman', 'module' => 'shipments', 'action' => 'update', 'description' => 'Posting shipment dan unggah proof of delivery.'],
        'complaints.view' => ['label' => 'Lihat Komplain B2B', 'module' => 'complaints', 'action' => 'view', 'description' => 'Melihat komplain pelanggan B2B.'],
        'complaints.create' => ['label' => 'Buat Komplain B2B', 'module' => 'complaints', 'action' => 'create', 'description' => 'Mengajukan komplain pengiriman/order B2B.'],
        'reports.view' => ['label' => 'Lihat Laporan', 'module' => 'reports', 'action' => 'view', 'description' => 'Melihat laporan.'],
        'reports.export' => ['label' => 'Export Laporan', 'module' => 'reports', 'action' => 'export', 'description' => 'Mengunduh laporan.'],
        'notifications.view' => ['label' => 'Lihat Notifikasi', 'module' => 'notifications', 'action' => 'view', 'description' => 'Melihat channel, template, jadwal, penerima, alert, dan log notifikasi.'],
        'notifications.update' => ['label' => 'Kelola Notifikasi', 'module' => 'notifications', 'action' => 'update', 'description' => 'Mengubah konfigurasi channel, template, jadwal, penerima, dan alert notifikasi.'],
        'whatsapp_connection.view' => ['label' => 'Lihat Koneksi WhatsApp', 'module' => 'whatsapp_connection', 'action' => 'view', 'description' => 'Melihat status koneksi WhatsApp perusahaan.'],
        'whatsapp_connection.manage' => ['label' => 'Kelola Koneksi WhatsApp', 'module' => 'whatsapp_connection', 'action' => 'manage', 'description' => 'Menghubungkan dan memutus WhatsApp perusahaan.'],
        'notifications.send' => ['label' => 'Kirim/Retry Notifikasi', 'module' => 'notifications', 'action' => 'create', 'description' => 'Menjalankan test message, run now jadwal, dan retry pengiriman.'],
        'margins.view_sensitive' => ['label' => 'Lihat Margin/HPP Sensitif', 'module' => 'margins', 'action' => 'view_sensitive', 'description' => 'Melihat HPP, margin, dan data sensitif.'],
        'approvals.view' => ['label' => 'Lihat Approval', 'module' => 'approvals', 'action' => 'view', 'description' => 'Melihat daftar approval.'],
        'approvals.approve' => ['label' => 'Approve Dokumen', 'module' => 'approvals', 'action' => 'approve', 'description' => 'Menyetujui dokumen sensitif.'],
        'audit.view' => ['label' => 'Lihat Audit Log', 'module' => 'audit', 'action' => 'view', 'description' => 'Melihat audit log, keamanan, dan anomali.'],
        'audit.resolve' => ['label' => 'Resolve Anomali', 'module' => 'audit', 'action' => 'approve', 'description' => 'Meninjau dan menutup alert anomali.'],
        'audit.export' => ['label' => 'Export Audit Log', 'module' => 'audit', 'action' => 'export', 'description' => 'Mengunduh audit log aman.'],
    ],

    'roles' => [
        'owner_viewer' => ['label' => 'Owner Viewer', 'description' => 'Owner read-only untuk pemantauan bisnis tanpa tugas approval operasional.', 'permissions' => ['*.view', 'finance_annual.view', 'finance_annual.export', 'audit.view', 'audit.export', 'reports.export', 'notifications.view', 'margins.view_sensitive', 'work_checklists.view_own', 'work_checklists.update_own', 'work_checklists.view_all', 'work_checklists.export', 'staff_bonuses.view_all', 'staff_bonuses.export']],
        'owner_approver' => ['label' => 'Owner Pengelola', 'description' => 'Owner mengelola target dan memantau hasil tanpa tugas approval operasional.', 'permissions' => ['*.view', 'finance_annual.view', 'finance_annual.export', 'audit.view', 'audit.export', 'reports.export', 'notifications.view', 'notifications.update', 'notifications.send', 'margins.view_sensitive', 'work_checklists.view_own', 'work_checklists.update_own', 'work_checklists.view_all', 'work_checklists.export', 'staff_bonuses.view_all', 'staff_bonuses.manage', 'staff_bonuses.pay', 'staff_bonuses.export']],
        'super_admin' => ['label' => 'Super Admin', 'description' => 'Akses penuh sistem.', 'permissions' => ['*']],
        'admin_user' => ['label' => 'Admin User', 'description' => 'Mengelola user dan lokasi kerja.', 'permissions' => ['dashboard.view', 'admin.users.*', 'work_checklists.view_own', 'work_checklists.update_own']],
        'admin_config' => ['label' => 'Admin Config', 'description' => 'Konfigurasi master organisasi, sistem, pajak, dan tindak lanjut anomali.', 'permissions' => ['whatsapp_connection.view', 'whatsapp_connection.manage', 'dashboard.view', 'admin.warehouses.*', 'admin.branches.*', 'admin.settings.*', 'products.*', 'product_requests.view', 'suppliers.*', 'customers.*', 'prices.view', 'prices.update', 'notifications.*', 'sales.performance.view', 'sales.targets.manage', 'sales.customers.assign', 'tax.*', 'approvals.view', 'audit.view', 'audit.resolve', 'audit.export', 'margins.view_sensitive', 'system.health.view', 'work_checklists.view_own', 'work_checklists.update_own', 'work_checklists.manage_templates']],
        'staf_keuangan' => ['label' => 'Staf Keuangan', 'description' => 'Menyusun rekap bulanan dan laporan tahunan.', 'permissions' => ['dashboard.view', 'finance_annual.view', 'finance_annual.manage', 'finance_annual.export', 'work_checklists.view_own', 'work_checklists.update_own']],
        'kepala_keuangan' => ['label' => 'Kepala Keuangan', 'description' => 'Memeriksa, menyetujui, dan mengunci laporan keuangan.', 'permissions' => ['dashboard.view', 'finance_annual.view', 'finance_annual.manage', 'finance_annual.approve', 'finance_annual.export', 'reports.view', 'work_checklists.view_own', 'work_checklists.update_own']],
        'kepala_gudang' => ['label' => 'Kepala Gudang', 'description' => 'Kepala bagian gudang dan pemegang approval operasional gudang.', 'permissions' => ['staff_bonuses.view_own', 'staff_bonuses.view_team', 'staff_bonuses.approve', 'dashboard.view', 'admin.warehouses.view', 'products.*', 'product_requests.view', 'suppliers.view', 'suppliers.create', 'suppliers.update', 'suppliers.import', 'suppliers.export', 'customers.*', 'prices.view', 'prices.update', 'prices.approve', 'margins.view_sensitive', 'stock.*', 'stock_transfers.*', 'stock_adjustments.*', 'returns.*', 'losses.*', 'purchase_orders.view', 'purchase_orders.approve', 'goods_receipts.*', 'b2b_orders.view', 'b2b_orders.approve', 'invoices.*', 'receivables.*', 'attendance.*', 'payments.create', 'payments.verify', 'shipments.*', 'complaints.view', 'reports.view', 'approvals.view', 'approvals.approve', 'work_checklists.view_own', 'work_checklists.update_own', 'work_checklists.view_team', 'work_checklists.export']],
        'staff_gudang' => ['label' => 'Staff Gudang', 'description' => 'Pelaksana transaksi gudang.', 'permissions' => ['staff_bonuses.view_own', 'dashboard.view', 'products.view', 'suppliers.view', 'customers.view', 'stock.view', 'stock.create', 'stock_transfers.view', 'stock_transfers.create', 'stock_transfers.pack', 'stock_transfers.ship', 'stock_adjustments.view', 'stock_adjustments.create', 'returns.view', 'returns.create', 'returns.inspect', 'losses.view', 'losses.create', 'goods_receipts.view', 'goods_receipts.create', 'b2b_orders.view', 'invoices.view', 'receivables.view', 'receivables.pay', 'receivables.remind', 'attendance.check', 'payments.create', 'shipments.view', 'shipments.create', 'shipments.update', 'complaints.view', 'work_checklists.view_own', 'work_checklists.update_own']],
        'picker_packer' => ['label' => 'Picker Packer', 'description' => 'Picking dan packing order.', 'permissions' => ['staff_bonuses.view_own', 'dashboard.view', 'products.view', 'stock.view', 'stock_transfers.view', 'stock_transfers.pack', 'stock_adjustments.view', 'stock_adjustments.create', 'b2b_orders.view', 'shipments.view', 'shipments.update', 'attendance.check', 'work_checklists.view_own', 'work_checklists.update_own']],
        'purchasing' => ['label' => 'Purchasing', 'description' => 'Pembelian dan PO.', 'permissions' => ['dashboard.view', 'products.view', 'products.export', 'suppliers.*', 'prices.view', 'stock.view', 'purchase_orders.view', 'purchase_orders.create', 'purchase_orders.export', 'goods_receipts.view', 'reports.view', 'work_checklists.view_own', 'work_checklists.update_own']],
        'kepala_toko' => ['label' => 'Kepala Toko', 'description' => 'Kepala bagian toko/cabang dan pemegang approval operasional toko.', 'permissions' => ['staff_bonuses.view_own', 'staff_bonuses.view_team', 'staff_bonuses.approve', 'dashboard.view', 'retail.catalog.view', 'retail.catalog.manage', 'emergency_purchases.*', 'emergency_reports.view', 'product_requests.view', 'product_requests.create', 'product_requests.approve', 'purchase_orders.view', 'purchase_orders.create', 'purchase_orders.approve', 'goods_receipts.view', 'goods_receipts.create', 'admin.branches.view', 'products.view', 'products.print_barcode', 'customers.view', 'customers.create', 'customers.update', 'prices.view', 'prices.approve', 'stock.view', 'stock_transfers.view', 'stock_transfers.create', 'stock_transfers.approve', 'stock_transfers.receive', 'stock_adjustments.view', 'stock_adjustments.create', 'stock_adjustments.approve', 'returns.view', 'returns.create', 'returns.approve', 'pos.view', 'pos.void', 'cash_shifts.*', 'receivables.view', 'receivables.pay', 'receivables.approve', 'receivables.remind', 'attendance.*', 'reports.view', 'approvals.view', 'approvals.approve', 'work_checklists.view_own', 'work_checklists.update_own', 'work_checklists.view_team', 'work_checklists.export']],
        'staf_toko' => ['label' => 'Staf Toko', 'description' => 'Melayani pelanggan dengan melihat etalase, harga, stok, dan lokasi pajang produk di toko penugasan.', 'permissions' => ['staff_bonuses.view_own', 'dashboard.view', 'retail.catalog.view', 'emergency_purchases.view', 'emergency_purchases.create', 'product_requests.view', 'product_requests.create', 'attendance.check', 'work_checklists.view_own', 'work_checklists.update_own']],
        'kasir' => ['label' => 'Kasir', 'description' => 'Transaksi POS dan shift kas.', 'permissions' => ['staff_bonuses.view_own', 'dashboard.view', 'products.view', 'prices.view', 'pos.view', 'pos.create', 'emergency_purchases.view', 'emergency_purchases.create', 'emergency_purchases.purchase', 'cash_shifts.view', 'cash_shifts.create', 'receivables.view', 'receivables.pay', 'attendance.check', 'work_checklists.view_own', 'work_checklists.update_own']],
        'supervisor_shift' => ['label' => 'Supervisor Shift', 'description' => 'Memantau shift dan operasional toko tanpa otoritas approval kepala bagian.', 'permissions' => ['staff_bonuses.view_own', 'staff_bonuses.view_team', 'dashboard.view', 'pos.view', 'pos.void', 'cash_shifts.view', 'cash_shifts.create', 'stock_transfers.view', 'stock_transfers.receive', 'receivables.view', 'receivables.pay', 'receivables.remind', 'attendance.view', 'attendance.check', 'attendance.update', 'reports.view', 'work_checklists.view_own', 'work_checklists.update_own', 'work_checklists.view_team', 'work_checklists.export']],
        'langganan_owner' => ['label' => 'Langganan Owner', 'description' => 'Owner pelanggan B2B.', 'permissions' => ['dashboard.view', 'customers.view_own', 'b2b_orders.view', 'b2b_orders.create', 'receivables.view', 'payments.create', 'complaints.create', 'complaints.view']],
        'langganan_staff' => ['label' => 'Langganan Staff', 'description' => 'Staff pelanggan B2B.', 'permissions' => ['dashboard.view', 'customers.view_own', 'b2b_orders.view', 'b2b_orders.create', 'receivables.view', 'payments.create', 'complaints.create', 'complaints.view']],
        'sales' => ['label' => 'Sales', 'description' => 'Membuat order B2B dan memantau customer, target, bonus, serta stok dalam lingkup sendiri.', 'permissions' => ['staff_bonuses.view_own', 'dashboard.view', 'sales.dashboard.view', 'sales.customers.view_own', 'sales.orders.view_own', 'sales.orders.create', 'sales.stock.view', 'sales.targets.view_own', 'work_checklists.view_own', 'work_checklists.update_own']],
    ],
];
