<?php

return [
    'actions' => ['view', 'create', 'update', 'approve', 'void', 'export', 'view_sensitive'],

    'permissions' => [
        'dashboard.view' => ['label' => 'Lihat Dashboard', 'module' => 'dashboard', 'action' => 'view', 'description' => 'Mengakses dashboard sesuai role.'],
        'admin.users.view' => ['label' => 'Lihat Pengguna', 'module' => 'admin.users', 'action' => 'view', 'description' => 'Melihat daftar dan detail pengguna.'],
        'admin.users.create' => ['label' => 'Tambah Pengguna', 'module' => 'admin.users', 'action' => 'create', 'description' => 'Membuat akun pengguna baru.'],
        'admin.users.update' => ['label' => 'Ubah Pengguna', 'module' => 'admin.users', 'action' => 'update', 'description' => 'Mengubah profil, status, dan role pengguna.'],
        'admin.users.assign_locations' => ['label' => 'Atur Lokasi Pengguna', 'module' => 'admin.users', 'action' => 'update', 'description' => 'Menugaskan lokasi kerja pengguna.'],
        'admin.users.reset_password' => ['label' => 'Reset Password Pengguna', 'module' => 'admin.users', 'action' => 'update', 'description' => 'Mengirim link reset password pengguna.'],
        'admin.users.export' => ['label' => 'Export Pengguna', 'module' => 'admin.users', 'action' => 'export', 'description' => 'Mengunduh daftar pengguna.'],
        'admin.roles.view' => ['label' => 'Lihat Role', 'module' => 'admin.roles', 'action' => 'view', 'description' => 'Melihat role dan matriks permission.'],
        'admin.roles.create' => ['label' => 'Tambah Role', 'module' => 'admin.roles', 'action' => 'create', 'description' => 'Membuat role baru.'],
        'admin.roles.update' => ['label' => 'Ubah Role', 'module' => 'admin.roles', 'action' => 'update', 'description' => 'Mengubah metadata role dan permission.'],
        'admin.permissions.view' => ['label' => 'Lihat Permission', 'module' => 'admin.permissions', 'action' => 'view', 'description' => 'Melihat daftar permission sistem.'],
        'admin.warehouses.view' => ['label' => 'Lihat Gudang', 'module' => 'admin.warehouses', 'action' => 'view', 'description' => 'Melihat daftar dan detail gudang.'],
        'admin.warehouses.create' => ['label' => 'Tambah Gudang', 'module' => 'admin.warehouses', 'action' => 'create', 'description' => 'Membuat master gudang.'],
        'admin.warehouses.update' => ['label' => 'Ubah Gudang', 'module' => 'admin.warehouses', 'action' => 'update', 'description' => 'Mengubah master gudang dan status aktif.'],
        'admin.branches.view' => ['label' => 'Lihat Cabang/Toko', 'module' => 'admin.branches', 'action' => 'view', 'description' => 'Melihat daftar dan detail cabang/toko.'],
        'admin.branches.create' => ['label' => 'Tambah Cabang/Toko', 'module' => 'admin.branches', 'action' => 'create', 'description' => 'Membuat master cabang/toko.'],
        'admin.branches.update' => ['label' => 'Ubah Cabang/Toko', 'module' => 'admin.branches', 'action' => 'update', 'description' => 'Mengubah master cabang/toko dan status aktif.'],
        'admin.settings.view' => ['label' => 'Lihat Pengaturan Sistem', 'module' => 'admin.settings', 'action' => 'view', 'description' => 'Melihat pengaturan umum dan nomor dokumen.'],
        'admin.settings.update' => ['label' => 'Ubah Pengaturan Sistem', 'module' => 'admin.settings', 'action' => 'update', 'description' => 'Mengubah pengaturan umum dan nomor dokumen.'],
        'system.health.view' => ['label' => 'Lihat Kesehatan Sistem', 'module' => 'system.health', 'action' => 'view', 'description' => 'Mengakses halaman health check.'],
        'products.view' => ['label' => 'Lihat Produk', 'module' => 'products', 'action' => 'view', 'description' => 'Melihat master produk.'],
        'products.create' => ['label' => 'Tambah Produk', 'module' => 'products', 'action' => 'create', 'description' => 'Membuat master produk.'],
        'products.update' => ['label' => 'Ubah Produk', 'module' => 'products', 'action' => 'update', 'description' => 'Mengubah master produk.'],
        'products.import' => ['label' => 'Import Produk', 'module' => 'products', 'action' => 'create', 'description' => 'Mengimpor master produk dari Excel/CSV.'],
        'products.export' => ['label' => 'Export Produk', 'module' => 'products', 'action' => 'export', 'description' => 'Mengunduh master produk dan template import.'],
        'products.print_barcode' => ['label' => 'Cetak Barcode Produk', 'module' => 'products', 'action' => 'export', 'description' => 'Mencetak label barcode/QR produk.'],
        'suppliers.view' => ['label' => 'Lihat Supplier', 'module' => 'suppliers', 'action' => 'view', 'description' => 'Melihat master supplier.'],
        'suppliers.create' => ['label' => 'Tambah Supplier', 'module' => 'suppliers', 'action' => 'create', 'description' => 'Membuat master supplier.'],
        'suppliers.update' => ['label' => 'Ubah Supplier', 'module' => 'suppliers', 'action' => 'update', 'description' => 'Mengubah master supplier dan status aktif.'],
        'suppliers.import' => ['label' => 'Import Supplier', 'module' => 'suppliers', 'action' => 'create', 'description' => 'Mengimpor master supplier dari Excel/CSV.'],
        'suppliers.export' => ['label' => 'Export Supplier', 'module' => 'suppliers', 'action' => 'export', 'description' => 'Mengunduh master supplier.'],
        'customers.view' => ['label' => 'Lihat Pelanggan', 'module' => 'customers', 'action' => 'view', 'description' => 'Melihat master pelanggan.'],
        'customers.view_own' => ['label' => 'Lihat Pelanggan Sendiri', 'module' => 'customers', 'action' => 'view', 'description' => 'Melihat pelanggan B2B yang terhubung ke akun.'],
        'customers.create' => ['label' => 'Tambah Pelanggan', 'module' => 'customers', 'action' => 'create', 'description' => 'Membuat master pelanggan.'],
        'customers.update' => ['label' => 'Ubah Pelanggan', 'module' => 'customers', 'action' => 'update', 'description' => 'Mengubah master pelanggan dan status.'],
        'customers.manage_access' => ['label' => 'Kelola Akses B2B', 'module' => 'customers', 'action' => 'update', 'description' => 'Mengelola alamat kirim dan akun B2B pelanggan.'],
        'customers.manage_settings' => ['label' => 'Kelola Kredit dan Verifikasi', 'module' => 'customers', 'action' => 'approve', 'description' => 'Mengelola dokumen, status verifikasi, harga khusus, limit, dan termin.'],
        'customers.import' => ['label' => 'Import Pelanggan', 'module' => 'customers', 'action' => 'create', 'description' => 'Mengimpor master pelanggan dari Excel/CSV.'],
        'customers.export' => ['label' => 'Export Pelanggan', 'module' => 'customers', 'action' => 'export', 'description' => 'Mengunduh master pelanggan.'],
        'prices.view' => ['label' => 'Lihat Harga', 'module' => 'prices', 'action' => 'view', 'description' => 'Melihat daftar harga.'],
        'prices.update' => ['label' => 'Ubah Harga', 'module' => 'prices', 'action' => 'update', 'description' => 'Mengubah harga.'],
        'prices.approve' => ['label' => 'Approve Harga', 'module' => 'prices', 'action' => 'approve', 'description' => 'Menyetujui perubahan harga sensitif.'],
        'stock.view' => ['label' => 'Lihat Stok', 'module' => 'stock', 'action' => 'view', 'description' => 'Melihat stok lokasi.'],
        'stock.create' => ['label' => 'Buat Transaksi Stok', 'module' => 'stock', 'action' => 'create', 'description' => 'Membuat dokumen stok.'],
        'stock.update' => ['label' => 'Ubah Transaksi Stok', 'module' => 'stock', 'action' => 'update', 'description' => 'Mengubah dokumen stok draft.'],
        'stock_transfers.view' => ['label' => 'Lihat Transfer Stok', 'module' => 'stock_transfers', 'action' => 'view', 'description' => 'Melihat transfer stok.'],
        'stock_transfers.create' => ['label' => 'Buat Transfer Stok', 'module' => 'stock_transfers', 'action' => 'create', 'description' => 'Membuat transfer stok.'],
        'stock_transfers.approve' => ['label' => 'Approve Transfer Stok', 'module' => 'stock_transfers', 'action' => 'approve', 'description' => 'Menyetujui transfer stok.'],
        'stock_transfers.pack' => ['label' => 'Picking/Packing Transfer', 'module' => 'stock_transfers', 'action' => 'update', 'description' => 'Melakukan picking dan packing transfer stok.'],
        'stock_transfers.ship' => ['label' => 'Kirim Transfer Stok', 'module' => 'stock_transfers', 'action' => 'update', 'description' => 'Mengirim transfer stok.'],
        'stock_transfers.receive' => ['label' => 'Terima Transfer Stok', 'module' => 'stock_transfers', 'action' => 'create', 'description' => 'Mengonfirmasi penerimaan transfer di cabang.'],
        'stock_adjustments.view' => ['label' => 'Lihat Koreksi Stok', 'module' => 'stock_adjustments', 'action' => 'view', 'description' => 'Melihat koreksi stok.'],
        'stock_adjustments.create' => ['label' => 'Buat Koreksi Stok', 'module' => 'stock_adjustments', 'action' => 'create', 'description' => 'Membuat koreksi stok.'],
        'stock_adjustments.approve' => ['label' => 'Approve Koreksi Stok', 'module' => 'stock_adjustments', 'action' => 'approve', 'description' => 'Menyetujui koreksi stok.'],
        'returns.view' => ['label' => 'Lihat Retur', 'module' => 'returns', 'action' => 'view', 'description' => 'Melihat retur dan settlement.'],
        'returns.create' => ['label' => 'Buat Retur', 'module' => 'returns', 'action' => 'create', 'description' => 'Mengajukan retur.'],
        'returns.inspect' => ['label' => 'QC Retur', 'module' => 'returns', 'action' => 'update', 'description' => 'Melakukan pemeriksaan retur.'],
        'returns.approve' => ['label' => 'Approve Retur', 'module' => 'returns', 'action' => 'approve', 'description' => 'Menyetujui retur/loss bernilai besar.'],
        'returns.settle' => ['label' => 'Settlement Retur', 'module' => 'returns', 'action' => 'update', 'description' => 'Menyelesaikan refund, credit note, atau retur supplier.'],
        'losses.view' => ['label' => 'Lihat Loss', 'module' => 'losses', 'action' => 'view', 'description' => 'Melihat kerugian inventory.'],
        'losses.create' => ['label' => 'Catat Loss', 'module' => 'losses', 'action' => 'create', 'description' => 'Mencatat barang rusak/hilang.'],
        'purchase_orders.view' => ['label' => 'Lihat Purchase Order', 'module' => 'purchase_orders', 'action' => 'view', 'description' => 'Melihat PO pembelian.'],
        'purchase_orders.create' => ['label' => 'Buat Purchase Order', 'module' => 'purchase_orders', 'action' => 'create', 'description' => 'Membuat PO pembelian.'],
        'purchase_orders.approve' => ['label' => 'Approve Purchase Order', 'module' => 'purchase_orders', 'action' => 'approve', 'description' => 'Menyetujui PO pembelian.'],
        'purchase_orders.export' => ['label' => 'Export Purchase Order', 'module' => 'purchase_orders', 'action' => 'export', 'description' => 'Mengunduh daftar dan dokumen PO.'],
        'goods_receipts.view' => ['label' => 'Lihat Penerimaan Barang', 'module' => 'goods_receipts', 'action' => 'view', 'description' => 'Melihat penerimaan barang.'],
        'goods_receipts.create' => ['label' => 'Buat Penerimaan Barang', 'module' => 'goods_receipts', 'action' => 'create', 'description' => 'Mencatat penerimaan barang.'],
        'pos.view' => ['label' => 'Lihat POS', 'module' => 'pos', 'action' => 'view', 'description' => 'Mengakses transaksi POS.'],
        'pos.create' => ['label' => 'Buat Penjualan POS', 'module' => 'pos', 'action' => 'create', 'description' => 'Membuat penjualan POS.'],
        'pos.void' => ['label' => 'Void POS', 'module' => 'pos', 'action' => 'void', 'description' => 'Membatalkan transaksi POS dengan alasan.'],
        'cash_shifts.view' => ['label' => 'Lihat Shift Kas', 'module' => 'cash_shifts', 'action' => 'view', 'description' => 'Melihat shift kasir.'],
        'cash_shifts.create' => ['label' => 'Buka Shift Kas', 'module' => 'cash_shifts', 'action' => 'create', 'description' => 'Membuka shift kas.'],
        'cash_shifts.approve' => ['label' => 'Approve Closing Shift', 'module' => 'cash_shifts', 'action' => 'approve', 'description' => 'Menyetujui closing shift.'],
        'b2b_orders.view' => ['label' => 'Lihat Order B2B', 'module' => 'b2b_orders', 'action' => 'view', 'description' => 'Melihat order pelanggan langganan.'],
        'b2b_orders.create' => ['label' => 'Buat Order B2B', 'module' => 'b2b_orders', 'action' => 'create', 'description' => 'Membuat order B2B.'],
        'b2b_orders.approve' => ['label' => 'Approve Order B2B', 'module' => 'b2b_orders', 'action' => 'approve', 'description' => 'Menyetujui order B2B.'],
        'receivables.view' => ['label' => 'Lihat Piutang', 'module' => 'receivables', 'action' => 'view', 'description' => 'Melihat piutang pelanggan.'],
        'payments.create' => ['label' => 'Input Pembayaran', 'module' => 'payments', 'action' => 'create', 'description' => 'Mencatat pembayaran.'],
        'reports.view' => ['label' => 'Lihat Laporan', 'module' => 'reports', 'action' => 'view', 'description' => 'Melihat laporan.'],
        'reports.export' => ['label' => 'Export Laporan', 'module' => 'reports', 'action' => 'export', 'description' => 'Mengunduh laporan.'],
        'margins.view_sensitive' => ['label' => 'Lihat Margin/HPP Sensitif', 'module' => 'margins', 'action' => 'view_sensitive', 'description' => 'Melihat HPP, margin, dan data sensitif.'],
        'approvals.view' => ['label' => 'Lihat Approval', 'module' => 'approvals', 'action' => 'view', 'description' => 'Melihat daftar approval.'],
        'approvals.approve' => ['label' => 'Approve Dokumen', 'module' => 'approvals', 'action' => 'approve', 'description' => 'Menyetujui dokumen sensitif.'],
    ],

    'roles' => [
        'owner_viewer' => ['label' => 'Owner Viewer', 'description' => 'Owner read-only tanpa approval.', 'permissions' => ['*.view', 'reports.export', 'margins.view_sensitive']],
        'owner_approver' => ['label' => 'Owner Approver', 'description' => 'Owner dengan hak approval sensitif.', 'permissions' => ['*.view', '*.approve', 'reports.export', 'margins.view_sensitive']],
        'super_admin' => ['label' => 'Super Admin', 'description' => 'Akses penuh sistem.', 'permissions' => ['*']],
        'admin_user' => ['label' => 'Admin User', 'description' => 'Mengelola user dan lokasi kerja.', 'permissions' => ['dashboard.view', 'admin.users.*']],
        'admin_config' => ['label' => 'Admin Config', 'description' => 'Konfigurasi master organisasi dan sistem.', 'permissions' => ['dashboard.view', 'admin.warehouses.*', 'admin.branches.*', 'admin.settings.*', 'products.*', 'suppliers.*', 'customers.*', 'system.health.view']],
        'kepala_gudang' => ['label' => 'Kepala Gudang', 'description' => 'Supervisor operasional gudang.', 'permissions' => ['dashboard.view', 'admin.warehouses.view', 'products.*', 'suppliers.view', 'suppliers.create', 'suppliers.update', 'suppliers.import', 'suppliers.export', 'customers.*', 'stock.*', 'stock_transfers.*', 'stock_adjustments.*', 'returns.*', 'losses.*', 'purchase_orders.view', 'purchase_orders.approve', 'goods_receipts.*', 'reports.view']],
        'staff_gudang' => ['label' => 'Staff Gudang', 'description' => 'Pelaksana transaksi gudang.', 'permissions' => ['dashboard.view', 'products.view', 'suppliers.view', 'customers.view', 'stock.view', 'stock.create', 'stock_transfers.view', 'stock_transfers.create', 'stock_transfers.pack', 'stock_transfers.ship', 'stock_adjustments.view', 'stock_adjustments.create', 'returns.view', 'returns.create', 'returns.inspect', 'losses.view', 'losses.create', 'goods_receipts.view', 'goods_receipts.create']],
        'picker_packer' => ['label' => 'Picker Packer', 'description' => 'Picking dan packing order.', 'permissions' => ['dashboard.view', 'products.view', 'stock.view', 'stock_transfers.view', 'stock_transfers.pack', 'stock_adjustments.view', 'stock_adjustments.create', 'b2b_orders.view']],
        'purchasing' => ['label' => 'Purchasing', 'description' => 'Pembelian dan PO.', 'permissions' => ['dashboard.view', 'products.view', 'products.export', 'suppliers.*', 'stock.view', 'purchase_orders.view', 'purchase_orders.create', 'purchase_orders.export', 'goods_receipts.view', 'reports.view']],
        'kepala_toko' => ['label' => 'Kepala Toko', 'description' => 'Supervisor toko/cabang.', 'permissions' => ['dashboard.view', 'admin.branches.view', 'products.view', 'products.print_barcode', 'customers.view', 'customers.create', 'customers.update', 'prices.view', 'stock.view', 'stock_transfers.view', 'stock_transfers.create', 'stock_transfers.receive', 'stock_adjustments.view', 'stock_adjustments.create', 'returns.view', 'returns.create', 'pos.view', 'pos.void', 'cash_shifts.*', 'reports.view']],
        'kasir' => ['label' => 'Kasir', 'description' => 'Transaksi POS dan shift kas.', 'permissions' => ['dashboard.view', 'products.view', 'prices.view', 'pos.view', 'pos.create', 'cash_shifts.view', 'cash_shifts.create']],
        'supervisor_shift' => ['label' => 'Supervisor Shift', 'description' => 'Closing dan void shift.', 'permissions' => ['dashboard.view', 'pos.view', 'pos.void', 'cash_shifts.*', 'stock_transfers.view', 'stock_transfers.receive', 'reports.view']],
        'langganan_owner' => ['label' => 'Langganan Owner', 'description' => 'Owner pelanggan B2B.', 'permissions' => ['dashboard.view', 'customers.view_own', 'b2b_orders.view', 'b2b_orders.create', 'receivables.view', 'payments.create']],
        'langganan_staff' => ['label' => 'Langganan Staff', 'description' => 'Staff pelanggan B2B.', 'permissions' => ['dashboard.view', 'customers.view_own', 'b2b_orders.view', 'b2b_orders.create']],
    ],
];
