<?php

return [
    'guides' => [
        'umum' => [
            'title' => 'Panduan Umum Pengguna',
            'short_title' => 'Panduan Umum',
            'description' => 'Dasar penggunaan aplikasi, keamanan akun, navigasi, status transaksi, bantuan, dan troubleshooting.',
            'icon' => 'ki-outline ki-information-5',
            'color' => 'primary',
            'roles' => ['*'],
            'file' => 'guide/umum.md',
        ],
        'owner' => [
            'title' => 'Panduan Owner',
            'short_title' => 'Owner',
            'description' => 'Dashboard bisnis, approval, audit, margin, laporan, stok, supplier, dan piutang.',
            'icon' => 'ki-outline ki-chart-line-up',
            'color' => 'success',
            'roles' => ['owner_viewer', 'owner_approver'],
            'file' => 'guide/owner.md',
        ],
        'super-admin' => [
            'title' => 'Panduan Super Admin',
            'short_title' => 'Super Admin',
            'description' => 'User, role, master data, konfigurasi, backup, import data awal, keamanan, dan go-live.',
            'icon' => 'ki-outline ki-security-user',
            'color' => 'danger',
            'roles' => ['super_admin', 'admin_user', 'admin_config'],
            'file' => 'guide/super-admin.md',
        ],
        'gudang' => [
            'title' => 'Panduan Operasional Gudang',
            'short_title' => 'Gudang',
            'description' => 'Stok, penerimaan, transfer, picking, fulfillment, opname, retur, loss, dan HPP.',
            'icon' => 'ki-outline ki-delivery-3',
            'color' => 'info',
            'roles' => ['kepala_gudang', 'staff_gudang', 'picker_packer'],
            'file' => 'guide/gudang.md',
        ],
        'purchasing-supplier' => [
            'title' => 'Panduan Purchasing & Supplier',
            'short_title' => 'Purchasing & Supplier',
            'description' => 'Master supplier, permintaan pembelian, Purchase Order, penerimaan, HPP, dan evaluasi supplier.',
            'icon' => 'ki-outline ki-handcart',
            'color' => 'warning',
            'roles' => ['purchasing', 'supplier'],
            'file' => 'guide/purchasing-supplier.md',
        ],
        'toko-internal' => [
            'title' => 'Panduan Toko Internal',
            'short_title' => 'Toko Internal',
            'description' => 'POS, shift kasir, closing, restock, transfer masuk, retur, piutang, dan kehadiran.',
            'icon' => 'ki-outline ki-shop',
            'color' => 'primary',
            'roles' => ['kepala_toko', 'kasir', 'supervisor_shift'],
            'file' => 'guide/toko-internal.md',
        ],
        'langganan-b2b' => [
            'title' => 'Panduan Langganan/B2B',
            'short_title' => 'Langganan/B2B',
            'description' => 'Katalog, keranjang, checkout, order, invoice, pembayaran, pengiriman, dan komplain.',
            'icon' => 'ki-outline ki-basket',
            'color' => 'success',
            'roles' => ['langganan_owner', 'langganan_staff'],
            'file' => 'guide/langganan-b2b.md',
        ],
    ],
];
