@extends('layouts.metronic.app')

@section('title', 'Detail Restok '.$restockRequest->number.' - '.config('app.name'))
@section('page_title', 'Detail Permintaan Restok')
@section('toolbar_actions')<a href="{{ route('retail.restock-requests.index') }}" class="btn btn-light"><i class="ki-outline ki-arrow-left fs-5 me-1"></i>Daftar Restok</a>@endsection

@section('content')
    <x-metronic.card class="mb-6">
        <div class="d-flex flex-wrap justify-content-between gap-4"><div><div class="text-muted fs-8">PERMINTAAN</div><h2>{{ $restockRequest->number }}</h2><div class="text-muted">{{ $restockRequest->created_at?->format('d/m/Y H:i') }}</div></div><x-metronic.status-badge :status="$restockRequest->status" /></div>
        <div class="row g-4 mt-2"><div class="col-md-3"><div class="text-muted fs-8">CABANG TUJUAN</div><strong>{{ $restockRequest->branch?->name }}</strong></div><div class="col-md-3"><div class="text-muted fs-8">GUDANG SUMBER</div><strong>{{ $restockRequest->sourceWarehouse?->name ?: '-' }}</strong></div><div class="col-md-2"><div class="text-muted fs-8">REQUESTER</div><strong>{{ $restockRequest->requester?->name }}</strong></div><div class="col-md-2"><div class="text-muted fs-8">PRIORITAS</div><strong>{{ ucfirst($restockRequest->priority) }}</strong></div><div class="col-md-2"><div class="text-muted fs-8">DIBUTUHKAN</div><strong>{{ $restockRequest->needed_at?->format('d/m/Y') ?: '-' }}</strong></div></div>
    </x-metronic.card>
    <div class="row g-6"><div class="col-xl-8"><x-metronic.card title="Item Restok"><div class="table-responsive"><table class="table table-row-dashed align-middle"><thead><tr class="text-muted fw-bold text-uppercase fs-7"><th>Produk</th><th>Unit</th><th>Qty Diminta</th><th>Qty Disetujui</th><th>Prioritas</th><th>Alasan</th></tr></thead><tbody>@foreach($restockRequest->items as $item)<tr><td><strong>{{ $item->product?->sku }}</strong><div class="text-muted">{{ $item->product?->name }}</div></td><td>{{ $item->product?->baseUnit?->symbol ?: '-' }}</td><td>{{ qty($item->quantity_requested) }}</td><td>{{ qty($item->quantity_approved) }}</td><td>{{ ucfirst($item->priority) }}</td><td>{{ $item->notes ?: '-' }}</td></tr>@endforeach</tbody></table></div></x-metronic.card></div><div class="col-xl-4"><x-metronic.card title="Transfer Terkait">@forelse($restockRequest->stockTransfers as $transfer)<a href="{{ route('warehouse.stock-transfers.show', $transfer) }}" class="d-flex align-items-center justify-content-between border rounded p-4 text-decoration-none"><div><strong>{{ $transfer->number }}</strong><div class="text-muted fs-8">{{ $transfer->transfer_date?->format('d/m/Y') }}</div></div><x-metronic.status-badge :status="$transfer->status" /></a>@empty<div class="text-muted">Belum dibuat menjadi transfer stok.</div>@endforelse</x-metronic.card></div></div>
    <x-metronic.card title="Riwayat Status" class="mt-6">@forelse($restockRequest->statusHistories as $history)<div class="border-start border-3 border-primary ps-4 mb-4"><strong>{{ $history->from_status ?: 'Awal' }} &rarr; {{ $history->to_status }}</strong><div class="text-muted fs-8">{{ $history->created_at?->format('d/m/Y H:i') }} oleh {{ $history->actor?->name ?: '-' }}</div><div>{{ $history->notes }}</div></div>@empty<div class="text-muted">Belum ada riwayat.</div>@endforelse</x-metronic.card>
@endsection
